/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import java.awt.CardLayout;
import java.awt.Color;
import model.Admin;
import model.User;

/**
 *
 * @author xuanchen
 */
public class Admin_Dashboard extends javax.swing.JFrame {

    private User user;
    CardLayout cardLayout;
    
    public Admin_Dashboard(User user) {
        initComponents();
        
        this.user = user;
        welcomeLbl.setText("Welcome " + user.getName());
        cardLayout = (CardLayout)pages.getLayout();
        
        cardLayout.show(pages, "dashboardPage");
        setActiveButton(dashboardBtn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        sidebar = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        dashboardBtn = new javax.swing.JButton();
        usersBtn = new javax.swing.JButton();
        assignmentsBtn = new javax.swing.JButton();
        assetsBtn = new javax.swing.JButton();
        ratesBtn = new javax.swing.JButton();
        insuranceBtn = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        profileBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        pages = new javax.swing.JPanel();
        dashboardPage = new javax.swing.JPanel();
        usersPage = new javax.swing.JPanel();
        assignmentsPage = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        doctorNameTf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctorTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        doctorNameTf1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        managerTable = new javax.swing.JTable();
        assignBtn = new javax.swing.JButton();
        assetsPage = new javax.swing.JPanel();
        assetNameTf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        assetTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        assetLbl = new javax.swing.JLabel();
        statusCb = new javax.swing.JComboBox<>();
        capacityTf = new javax.swing.JTextField();
        departmentCb = new javax.swing.JComboBox<>();
        openingTf = new javax.swing.JTextField();
        closingTf = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        ratesPage = new javax.swing.JPanel();
        insurancePage = new javax.swing.JPanel();
        profilePage = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(740, 160));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Hospital Management Sytem");

        welcomeLbl.setFont(new java.awt.Font("Heiti TC", 1, 12)); // NOI18N
        welcomeLbl.setForeground(new java.awt.Color(0, 0, 0));
        welcomeLbl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        welcomeLbl.setText("Welcome");
        welcomeLbl.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 530, Short.MAX_VALUE)
                .addComponent(welcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(welcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.NORTH);

        jSplitPane1.setDividerLocation(195);
        jSplitPane1.setDividerSize(0);

        sidebar.setBackground(new java.awt.Color(102, 204, 255));
        sidebar.setMaximumSize(new java.awt.Dimension(200, 500));
        sidebar.setPreferredSize(new java.awt.Dimension(200, 478));
        sidebar.setLayout(new java.awt.BorderLayout());

        menuPanel.setBackground(new java.awt.Color(102, 204, 255));
        menuPanel.setPreferredSize(new java.awt.Dimension(185, 500));
        menuPanel.setLayout(new java.awt.GridLayout(10, 1, 0, 5));

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(50, 80));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 195, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        menuPanel.add(jPanel2);

        dashboardBtn.setBackground(new java.awt.Color(51, 51, 255));
        dashboardBtn.setFont(new java.awt.Font("Menlo", 0, 14)); // NOI18N
        dashboardBtn.setForeground(new java.awt.Color(0, 0, 0));
        dashboardBtn.setText("Dashboard");
        dashboardBtn.setAutoscrolls(true);
        dashboardBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        dashboardBtn.setBorderPainted(false);
        dashboardBtn.setContentAreaFilled(false);
        dashboardBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboardBtn.setFocusPainted(false);
        dashboardBtn.setFocusable(false);
        dashboardBtn.setMargin(new java.awt.Insets(0, 15, 0, 15));
        dashboardBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });
        menuPanel.add(dashboardBtn);

        usersBtn.setFont(new java.awt.Font("Menlo", 0, 14)); // NOI18N
        usersBtn.setForeground(new java.awt.Color(0, 0, 0));
        usersBtn.setText("Users");
        usersBtn.setAutoscrolls(true);
        usersBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        usersBtn.setBorderPainted(false);
        usersBtn.setContentAreaFilled(false);
        usersBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usersBtn.setFocusPainted(false);
        usersBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        usersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersBtnActionPerformed(evt);
            }
        });
        menuPanel.add(usersBtn);

        assignmentsBtn.setFont(new java.awt.Font("Menlo", 0, 14)); // NOI18N
        assignmentsBtn.setForeground(new java.awt.Color(0, 0, 0));
        assignmentsBtn.setText("Assignments");
        assignmentsBtn.setToolTipText("");
        assignmentsBtn.setAutoscrolls(true);
        assignmentsBtn.setBorder(null);
        assignmentsBtn.setBorderPainted(false);
        assignmentsBtn.setContentAreaFilled(false);
        assignmentsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        assignmentsBtn.setFocusPainted(false);
        assignmentsBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        assignmentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmentsBtnActionPerformed(evt);
            }
        });
        menuPanel.add(assignmentsBtn);

        assetsBtn.setFont(new java.awt.Font("Menlo", 0, 14)); // NOI18N
        assetsBtn.setForeground(new java.awt.Color(0, 0, 0));
        assetsBtn.setText("Assets");
        assetsBtn.setToolTipText("");
        assetsBtn.setAutoscrolls(true);
        assetsBtn.setBorder(null);
        assetsBtn.setBorderPainted(false);
        assetsBtn.setContentAreaFilled(false);
        assetsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        assetsBtn.setFocusPainted(false);
        assetsBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        assetsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assetsBtnActionPerformed(evt);
            }
        });
        menuPanel.add(assetsBtn);

        ratesBtn.setFont(new java.awt.Font("Menlo", 0, 14)); // NOI18N
        ratesBtn.setForeground(new java.awt.Color(0, 0, 0));
        ratesBtn.setText("Consultation Rates");
        ratesBtn.setAutoscrolls(true);
        ratesBtn.setBorder(null);
        ratesBtn.setBorderPainted(false);
        ratesBtn.setContentAreaFilled(false);
        ratesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ratesBtn.setFocusPainted(false);
        ratesBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        ratesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratesBtnActionPerformed(evt);
            }
        });
        menuPanel.add(ratesBtn);

        insuranceBtn.setFont(new java.awt.Font("Menlo", 0, 14)); // NOI18N
        insuranceBtn.setForeground(new java.awt.Color(0, 0, 0));
        insuranceBtn.setText("Insurance Networks");
        insuranceBtn.setAutoscrolls(true);
        insuranceBtn.setBorder(null);
        insuranceBtn.setBorderPainted(false);
        insuranceBtn.setContentAreaFilled(false);
        insuranceBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insuranceBtn.setFocusPainted(false);
        insuranceBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        insuranceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceBtnActionPerformed(evt);
            }
        });
        menuPanel.add(insuranceBtn);

        jPanel7.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 195, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        menuPanel.add(jPanel7);

        profileBtn.setFont(new java.awt.Font("Menlo", 0, 14)); // NOI18N
        profileBtn.setForeground(new java.awt.Color(0, 0, 0));
        profileBtn.setText("Profile");
        profileBtn.setAutoscrolls(true);
        profileBtn.setBorder(null);
        profileBtn.setBorderPainted(false);
        profileBtn.setContentAreaFilled(false);
        profileBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profileBtn.setFocusPainted(false);
        profileBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnActionPerformed(evt);
            }
        });
        menuPanel.add(profileBtn);

        logoutBtn.setFont(new java.awt.Font("Menlo", 0, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(0, 0, 0));
        logoutBtn.setText("Logout");
        logoutBtn.setAutoscrolls(true);
        logoutBtn.setBorder(null);
        logoutBtn.setBorderPainted(false);
        logoutBtn.setContentAreaFilled(false);
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.setFocusPainted(false);
        logoutBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        menuPanel.add(logoutBtn);

        sidebar.add(menuPanel, java.awt.BorderLayout.NORTH);

        jSplitPane1.setLeftComponent(sidebar);

        pages.setLayout(new java.awt.CardLayout());

        dashboardPage.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout dashboardPageLayout = new javax.swing.GroupLayout(dashboardPage);
        dashboardPage.setLayout(dashboardPageLayout);
        dashboardPageLayout.setHorizontalGroup(
            dashboardPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        dashboardPageLayout.setVerticalGroup(
            dashboardPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1083, Short.MAX_VALUE)
        );

        pages.add(dashboardPage, "dashboardPage");

        usersPage.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout usersPageLayout = new javax.swing.GroupLayout(usersPage);
        usersPage.setLayout(usersPageLayout);
        usersPageLayout.setHorizontalGroup(
            usersPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        usersPageLayout.setVerticalGroup(
            usersPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1083, Short.MAX_VALUE)
        );

        pages.add(usersPage, "usersPage");

        assignmentsPage.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Search:");

        doctorNameTf.setBackground(new java.awt.Color(204, 204, 204));
        doctorNameTf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        doctorNameTf.setForeground(new java.awt.Color(0, 0, 0));
        doctorNameTf.setText("Name");
        doctorNameTf.setToolTipText("");

        doctorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "User ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        doctorTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(doctorTable);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Search:");

        doctorNameTf1.setBackground(new java.awt.Color(204, 204, 204));
        doctorNameTf1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        doctorNameTf1.setForeground(new java.awt.Color(0, 0, 0));
        doctorNameTf1.setText("Name");
        doctorNameTf1.setToolTipText("");

        managerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "User ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        managerTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(managerTable);

        assignBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        assignBtn.setText("Assign");

        javax.swing.GroupLayout assignmentsPageLayout = new javax.swing.GroupLayout(assignmentsPage);
        assignmentsPage.setLayout(assignmentsPageLayout);
        assignmentsPageLayout.setHorizontalGroup(
            assignmentsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assignmentsPageLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(assignmentsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(assignmentsPageLayout.createSequentialGroup()
                        .addGroup(assignmentsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(assignmentsPageLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(doctorNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86)
                        .addGroup(assignmentsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(assignmentsPageLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(doctorNameTf1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(assignmentsPageLayout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(assignBtn)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        assignmentsPageLayout.setVerticalGroup(
            assignmentsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assignmentsPageLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(assignmentsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(assignmentsPageLayout.createSequentialGroup()
                        .addGroup(assignmentsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorNameTf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(assignmentsPageLayout.createSequentialGroup()
                        .addGroup(assignmentsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(assignBtn)
                .addContainerGap(531, Short.MAX_VALUE))
        );

        pages.add(assignmentsPage, "assignmentsPage");

        assetsPage.setBackground(new java.awt.Color(255, 255, 255));

        assetNameTf.setBackground(new java.awt.Color(204, 204, 204));
        assetNameTf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        assetNameTf.setForeground(new java.awt.Color(0, 0, 0));
        assetNameTf.setText("Name");
        assetNameTf.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Search:");

        assetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Asset ID", "Name", "Type", "Status", "Capacity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        assetTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(assetTable);
        if (assetTable.getColumnModel().getColumnCount() > 0) {
            assetTable.getColumnModel().getColumn(0).setResizable(false);
            assetTable.getColumnModel().getColumn(1).setResizable(false);
            assetTable.getColumnModel().getColumn(2).setResizable(false);
            assetTable.getColumnModel().getColumn(3).setResizable(false);
            assetTable.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Selected Asset");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Asset:");
        jLabel6.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Status:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Capacity");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Department:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Operating From:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Operating To:");

        assetLbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        assetLbl.setForeground(new java.awt.Color(0, 0, 0));

        statusCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        departmentCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        updateBtn.setText("Update");

        javax.swing.GroupLayout assetsPageLayout = new javax.swing.GroupLayout(assetsPage);
        assetsPage.setLayout(assetsPageLayout);
        assetsPageLayout.setHorizontalGroup(
            assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assetsPageLayout.createSequentialGroup()
                .addGroup(assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(assetsPageLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(assetNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(assetsPageLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel5))
                    .addGroup(assetsPageLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(assetsPageLayout.createSequentialGroup()
                                .addGroup(assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel7))
                                .addGap(27, 27, 27)
                                .addGroup(assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(statusCb, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(openingTf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                            .addComponent(closingTf, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGroup(assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(capacityTf, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(departmentCb, javax.swing.GroupLayout.Alignment.LEADING, 0, 130, Short.MAX_VALUE)))
                                    .addGroup(assetsPageLayout.createSequentialGroup()
                                        .addComponent(assetLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3))))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateBtn))))
                .addContainerGap(348, Short.MAX_VALUE))
        );
        assetsPageLayout.setVerticalGroup(
            assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assetsPageLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assetNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(assetLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(statusCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(capacityTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(departmentCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(openingTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(closingTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(updateBtn)
                .addContainerGap(540, Short.MAX_VALUE))
        );

        pages.add(assetsPage, "assetsPage");

        ratesPage.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ratesPageLayout = new javax.swing.GroupLayout(ratesPage);
        ratesPage.setLayout(ratesPageLayout);
        ratesPageLayout.setHorizontalGroup(
            ratesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        ratesPageLayout.setVerticalGroup(
            ratesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1083, Short.MAX_VALUE)
        );

        pages.add(ratesPage, "ratesPage");

        insurancePage.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout insurancePageLayout = new javax.swing.GroupLayout(insurancePage);
        insurancePage.setLayout(insurancePageLayout);
        insurancePageLayout.setHorizontalGroup(
            insurancePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        insurancePageLayout.setVerticalGroup(
            insurancePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1083, Short.MAX_VALUE)
        );

        pages.add(insurancePage, "insurancePage");

        profilePage.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout profilePageLayout = new javax.swing.GroupLayout(profilePage);
        profilePage.setLayout(profilePageLayout);
        profilePageLayout.setHorizontalGroup(
            profilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        profilePageLayout.setVerticalGroup(
            profilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1083, Short.MAX_VALUE)
        );

        pages.add(profilePage, "profilePage");

        jSplitPane1.setRightComponent(pages);

        jPanel1.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1031, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1133, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setActiveButton(javax.swing.JButton activeButton) {
        javax.swing.JButton[] buttons = {dashboardBtn, usersBtn, assignmentsBtn, assetsBtn, ratesBtn, profileBtn, logoutBtn, insuranceBtn};
        
        for (javax.swing.JButton btn : buttons) {
            btn.setContentAreaFilled(false);
            btn.setOpaque(false);
            btn.setBorderPainted(false);
            btn.setFocusPainted(false);
            btn.setBackground(new java.awt.Color(102, 204, 255));
            btn.setForeground(Color.black);
        }
        
        activeButton.setContentAreaFilled(false);
        activeButton.setOpaque(true);
        activeButton.setBorderPainted(false);
        activeButton.setFocusPainted(false);
//        activeButton.setBackground(new java.awt.Color(70, 100, 220));
        activeButton.setBackground(Color.white);
        activeButton.setForeground(Color.black);
    }
    
    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        cardLayout.show(pages, "dashboardPage");
        setActiveButton(dashboardBtn);
        
    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void usersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersBtnActionPerformed
        cardLayout.show(pages, "usersPage");
        setActiveButton(usersBtn);
    }//GEN-LAST:event_usersBtnActionPerformed

    private void assignmentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignmentsBtnActionPerformed
        cardLayout.show(pages, "assignmentsPage");
        setActiveButton(assignmentsBtn);
    }//GEN-LAST:event_assignmentsBtnActionPerformed

    private void assetsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assetsBtnActionPerformed
        cardLayout.show(pages, "assetsPage");
        setActiveButton(assetsBtn);
    }//GEN-LAST:event_assetsBtnActionPerformed

    private void ratesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratesBtnActionPerformed
        cardLayout.show(pages, "ratesPage");
        setActiveButton(ratesBtn);
    }//GEN-LAST:event_ratesBtnActionPerformed

    private void profileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnActionPerformed
        cardLayout.show(pages, "profilePage");
        setActiveButton(profileBtn);
//        ChangePasswordDialog cpd = new ChangePasswordDialog(this,true);
//        cpd.setLocationRelativeTo(this);
//        cpd.setVisible(true);
    }//GEN-LAST:event_profileBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        setActiveButton(logoutBtn);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void insuranceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceBtnActionPerformed
        cardLayout.show(pages, "insurancePage");
        setActiveButton(insuranceBtn);
    }//GEN-LAST:event_insuranceBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                Admin testAdmin = new Admin("Uid001", "Test Admin", "admin@gmail.com", "123", "01234556", "Male", "admin");
                
                new Admin_Dashboard(testAdmin).setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel assetLbl;
    private javax.swing.JTextField assetNameTf;
    private javax.swing.JTable assetTable;
    private javax.swing.JButton assetsBtn;
    private javax.swing.JPanel assetsPage;
    private javax.swing.JButton assignBtn;
    private javax.swing.JButton assignmentsBtn;
    private javax.swing.JPanel assignmentsPage;
    private javax.swing.JTextField capacityTf;
    private javax.swing.JTextField closingTf;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JPanel dashboardPage;
    private javax.swing.JComboBox<String> departmentCb;
    private javax.swing.JTextField doctorNameTf;
    private javax.swing.JTextField doctorNameTf1;
    private javax.swing.JTable doctorTable;
    private javax.swing.JButton insuranceBtn;
    private javax.swing.JPanel insurancePage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTable managerTable;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTextField openingTf;
    private javax.swing.JPanel pages;
    private javax.swing.JButton profileBtn;
    private javax.swing.JPanel profilePage;
    private javax.swing.JButton ratesBtn;
    private javax.swing.JPanel ratesPage;
    private javax.swing.JPanel sidebar;
    private javax.swing.JComboBox<String> statusCb;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton usersBtn;
    private javax.swing.JPanel usersPage;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
