/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import java.awt.CardLayout;
import java.awt.Color;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Admin;
import model.ConsultationRate;
import model.HospitalAsset;
import model.InsuranceNetwork;
import model.User;
import repo.FileAssetRepo;
import service.AdminService;
import service.AssetService;
import service.ConfigurationService;

/**
 *
 * @author xuanchen
 */
public class Admin_Dashboard extends javax.swing.JFrame {

    private User user;
    CardLayout cardLayout;
    
    public Admin_Dashboard() {
        initComponents();
        
//        this.user = user;
//        welcomeLbl.setText("Welcome " + user.getName());
        cardLayout = (CardLayout)pages.getLayout();
        
        cardLayout.show(pages, "dashboardPage");
        setActiveButton(dashboardBtn);
        
        loadDashboardDetails();
        setupAssetFilter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        sidebar = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        dashboardBtn = new javax.swing.JButton();
        usersBtn = new javax.swing.JButton();
        assignmentsBtn = new javax.swing.JButton();
        assetsBtn = new javax.swing.JButton();
        ratesBtn = new javax.swing.JButton();
        insuranceBtn = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        profileBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        pages = new javax.swing.JPanel();
        dashboardPage = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        totalUserLbl = new javax.swing.JLabel();
        totalManagerLbl = new javax.swing.JLabel();
        totalDoctorLbl = new javax.swing.JLabel();
        totalPatientLbl = new javax.swing.JLabel();
        usersPage = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        createBtn = new javax.swing.JButton();
        updateUserBtn = new javax.swing.JButton();
        deleteUserBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        genderCb = new javax.swing.JComboBox<>();
        roleCb = new javax.swing.JComboBox<>();
        usernameTf = new javax.swing.JTextField();
        emailTf = new javax.swing.JTextField();
        phoneTf = new javax.swing.JTextField();
        userIdLbl = new javax.swing.JLabel();
        assignmentsPage = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        doctorNameTf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctorTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        doctorNameTf1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        managerTable = new javax.swing.JTable();
        assignBtn = new javax.swing.JButton();
        assetsPage = new javax.swing.JPanel();
        assetNameTf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        assetTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        assetLbl = new javax.swing.JLabel();
        statusCb = new javax.swing.JComboBox<>();
        capacityTf = new javax.swing.JTextField();
        departmentCb = new javax.swing.JComboBox<>();
        openingTf = new javax.swing.JTextField();
        closingTf = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        ratesPage = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        rateTable = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        baseRateTf = new javax.swing.JTextField();
        updateRateBtn = new javax.swing.JButton();
        consultationLbl = new javax.swing.JLabel();
        insurancePage = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        insuranceTable = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        updateInsuranceBtn = new javax.swing.JButton();
        insuranceLbl = new javax.swing.JLabel();
        insuranceStatusCb = new javax.swing.JComboBox<>();
        profilePage = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(740, 160));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Hospital Management Sytem");

        welcomeLbl.setFont(new java.awt.Font("Heiti TC", 1, 12)); // NOI18N
        welcomeLbl.setForeground(new java.awt.Color(0, 0, 0));
        welcomeLbl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        welcomeLbl.setText("Welcome");
        welcomeLbl.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 530, Short.MAX_VALUE)
                .addComponent(welcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(welcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.NORTH);

        jSplitPane1.setDividerLocation(195);
        jSplitPane1.setDividerSize(0);

        sidebar.setBackground(new java.awt.Color(102, 204, 255));
        sidebar.setMaximumSize(new java.awt.Dimension(200, 500));
        sidebar.setPreferredSize(new java.awt.Dimension(200, 478));
        sidebar.setLayout(new java.awt.BorderLayout());

        menuPanel.setBackground(new java.awt.Color(102, 204, 255));
        menuPanel.setPreferredSize(new java.awt.Dimension(185, 500));
        menuPanel.setLayout(new java.awt.GridLayout(10, 1, 0, 5));

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(50, 80));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        menuPanel.add(jPanel2);

        dashboardBtn.setBackground(new java.awt.Color(51, 51, 255));
        dashboardBtn.setFont(new java.awt.Font("Menlo", 0, 14)); // NOI18N
        dashboardBtn.setForeground(new java.awt.Color(0, 0, 0));
        dashboardBtn.setText("Dashboard");
        dashboardBtn.setAutoscrolls(true);
        dashboardBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        dashboardBtn.setBorderPainted(false);
        dashboardBtn.setContentAreaFilled(false);
        dashboardBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboardBtn.setFocusPainted(false);
        dashboardBtn.setFocusable(false);
        dashboardBtn.setMargin(new java.awt.Insets(0, 15, 0, 15));
        dashboardBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });
        menuPanel.add(dashboardBtn);

        usersBtn.setFont(new java.awt.Font("Menlo", 0, 14)); // NOI18N
        usersBtn.setForeground(new java.awt.Color(0, 0, 0));
        usersBtn.setText("Users");
        usersBtn.setAutoscrolls(true);
        usersBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        usersBtn.setBorderPainted(false);
        usersBtn.setContentAreaFilled(false);
        usersBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usersBtn.setFocusPainted(false);
        usersBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        usersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersBtnActionPerformed(evt);
            }
        });
        menuPanel.add(usersBtn);

        assignmentsBtn.setFont(new java.awt.Font("Menlo", 0, 14)); // NOI18N
        assignmentsBtn.setForeground(new java.awt.Color(0, 0, 0));
        assignmentsBtn.setText("Assignments");
        assignmentsBtn.setToolTipText("");
        assignmentsBtn.setAutoscrolls(true);
        assignmentsBtn.setBorder(null);
        assignmentsBtn.setBorderPainted(false);
        assignmentsBtn.setContentAreaFilled(false);
        assignmentsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        assignmentsBtn.setFocusPainted(false);
        assignmentsBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        assignmentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmentsBtnActionPerformed(evt);
            }
        });
        menuPanel.add(assignmentsBtn);

        assetsBtn.setFont(new java.awt.Font("Menlo", 0, 14)); // NOI18N
        assetsBtn.setForeground(new java.awt.Color(0, 0, 0));
        assetsBtn.setText("Assets");
        assetsBtn.setToolTipText("");
        assetsBtn.setAutoscrolls(true);
        assetsBtn.setBorder(null);
        assetsBtn.setBorderPainted(false);
        assetsBtn.setContentAreaFilled(false);
        assetsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        assetsBtn.setFocusPainted(false);
        assetsBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        assetsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assetsBtnActionPerformed(evt);
            }
        });
        menuPanel.add(assetsBtn);

        ratesBtn.setFont(new java.awt.Font("Menlo", 0, 14)); // NOI18N
        ratesBtn.setForeground(new java.awt.Color(0, 0, 0));
        ratesBtn.setText("Consultation Rates");
        ratesBtn.setAutoscrolls(true);
        ratesBtn.setBorder(null);
        ratesBtn.setBorderPainted(false);
        ratesBtn.setContentAreaFilled(false);
        ratesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ratesBtn.setFocusPainted(false);
        ratesBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        ratesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratesBtnActionPerformed(evt);
            }
        });
        menuPanel.add(ratesBtn);

        insuranceBtn.setFont(new java.awt.Font("Menlo", 0, 14)); // NOI18N
        insuranceBtn.setForeground(new java.awt.Color(0, 0, 0));
        insuranceBtn.setText("Insurance Networks");
        insuranceBtn.setAutoscrolls(true);
        insuranceBtn.setBorder(null);
        insuranceBtn.setBorderPainted(false);
        insuranceBtn.setContentAreaFilled(false);
        insuranceBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insuranceBtn.setFocusPainted(false);
        insuranceBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        insuranceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceBtnActionPerformed(evt);
            }
        });
        menuPanel.add(insuranceBtn);

        jPanel7.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        menuPanel.add(jPanel7);

        profileBtn.setFont(new java.awt.Font("Menlo", 0, 14)); // NOI18N
        profileBtn.setForeground(new java.awt.Color(0, 0, 0));
        profileBtn.setText("Profile");
        profileBtn.setAutoscrolls(true);
        profileBtn.setBorder(null);
        profileBtn.setBorderPainted(false);
        profileBtn.setContentAreaFilled(false);
        profileBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profileBtn.setFocusPainted(false);
        profileBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnActionPerformed(evt);
            }
        });
        menuPanel.add(profileBtn);

        logoutBtn.setFont(new java.awt.Font("Menlo", 0, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(0, 0, 0));
        logoutBtn.setText("Logout");
        logoutBtn.setAutoscrolls(true);
        logoutBtn.setBorder(null);
        logoutBtn.setBorderPainted(false);
        logoutBtn.setContentAreaFilled(false);
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.setFocusPainted(false);
        logoutBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        menuPanel.add(logoutBtn);

        sidebar.add(menuPanel, java.awt.BorderLayout.NORTH);

        jSplitPane1.setLeftComponent(sidebar);

        pages.setLayout(new java.awt.CardLayout());

        dashboardPage.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Total Users:");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Admin Dashboard");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Managers:");
        jLabel20.setToolTipText("");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Doctor:");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Patients:");

        totalUserLbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        totalUserLbl.setForeground(new java.awt.Color(0, 0, 0));

        totalManagerLbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        totalManagerLbl.setForeground(new java.awt.Color(0, 0, 0));

        totalDoctorLbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        totalDoctorLbl.setForeground(new java.awt.Color(0, 0, 0));

        totalPatientLbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        totalPatientLbl.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout dashboardPageLayout = new javax.swing.GroupLayout(dashboardPage);
        dashboardPage.setLayout(dashboardPageLayout);
        dashboardPageLayout.setHorizontalGroup(
            dashboardPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPageLayout.createSequentialGroup()
                .addGroup(dashboardPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardPageLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(dashboardPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(dashboardPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalUserLbl)
                            .addComponent(totalManagerLbl))
                        .addGap(215, 215, 215)
                        .addGroup(dashboardPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dashboardPageLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(totalDoctorLbl))
                            .addGroup(dashboardPageLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totalPatientLbl))))
                    .addGroup(dashboardPageLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel19)))
                .addContainerGap(398, Short.MAX_VALUE))
        );
        dashboardPageLayout.setVerticalGroup(
            dashboardPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPageLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel19)
                .addGap(51, 51, 51)
                .addGroup(dashboardPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel21)
                    .addComponent(totalUserLbl)
                    .addComponent(totalDoctorLbl))
                .addGap(50, 50, 50)
                .addGroup(dashboardPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel22)
                    .addComponent(totalManagerLbl)
                    .addComponent(totalPatientLbl))
                .addContainerGap(857, Short.MAX_VALUE))
        );

        pages.add(dashboardPage, "dashboardPage");

        usersPage.setBackground(new java.awt.Color(255, 255, 255));

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "Name", "Email", "Phone", "Gender", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userTable.getTableHeader().setReorderingAllowed(false);
        userTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(userTable);
        if (userTable.getColumnModel().getColumnCount() > 0) {
            userTable.getColumnModel().getColumn(0).setResizable(false);
            userTable.getColumnModel().getColumn(1).setResizable(false);
            userTable.getColumnModel().getColumn(2).setResizable(false);
            userTable.getColumnModel().getColumn(3).setResizable(false);
            userTable.getColumnModel().getColumn(4).setResizable(false);
            userTable.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("User ID:");
        jLabel23.setToolTipText("");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Name:");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Email:");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Phone:");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Gender:");

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Role:");

        createBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        updateUserBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        updateUserBtn.setText("Update");
        updateUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUserBtnActionPerformed(evt);
            }
        });

        deleteUserBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        deleteUserBtn.setText("Delete");
        deleteUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserBtnActionPerformed(evt);
            }
        });

        clearBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        genderCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        roleCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "MedicalManager", "Doctor", "Patient" }));

        usernameTf.setToolTipText("");

        userIdLbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        userIdLbl.setForeground(new java.awt.Color(0, 0, 0));
        userIdLbl.setToolTipText("");

        javax.swing.GroupLayout usersPageLayout = new javax.swing.GroupLayout(usersPage);
        usersPage.setLayout(usersPageLayout);
        usersPageLayout.setHorizontalGroup(
            usersPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersPageLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(usersPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usersPageLayout.createSequentialGroup()
                        .addComponent(createBtn)
                        .addGap(40, 40, 40)
                        .addComponent(updateUserBtn)
                        .addGap(40, 40, 40)
                        .addComponent(deleteUserBtn)
                        .addGap(40, 40, 40)
                        .addComponent(clearBtn))
                    .addGroup(usersPageLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(usersPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel28)
                            .addGroup(usersPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(usersPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel24))
                                .addGroup(usersPageLayout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addComponent(jLabel27)))
                            .addComponent(jLabel29))
                        .addGap(18, 18, 18)
                        .addGroup(usersPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(usersPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(genderCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(roleCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(usernameTf)
                                .addComponent(emailTf)
                                .addComponent(phoneTf, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(userIdLbl)))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        usersPageLayout.setVerticalGroup(
            usersPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersPageLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(usersPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(userIdLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(usersPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(usernameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(usersPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(emailTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(usersPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(phoneTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(usersPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(genderCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(usersPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(roleCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(usersPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createBtn)
                    .addComponent(updateUserBtn)
                    .addComponent(deleteUserBtn)
                    .addComponent(clearBtn))
                .addContainerGap(515, Short.MAX_VALUE))
        );

        pages.add(usersPage, "usersPage");

        assignmentsPage.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Search:");

        doctorNameTf.setBackground(new java.awt.Color(204, 204, 204));
        doctorNameTf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        doctorNameTf.setForeground(new java.awt.Color(0, 0, 0));
        doctorNameTf.setText("Name");
        doctorNameTf.setToolTipText("");

        doctorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "User ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        doctorTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(doctorTable);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Search:");

        doctorNameTf1.setBackground(new java.awt.Color(204, 204, 204));
        doctorNameTf1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        doctorNameTf1.setForeground(new java.awt.Color(0, 0, 0));
        doctorNameTf1.setText("Name");
        doctorNameTf1.setToolTipText("");

        managerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "User ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        managerTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(managerTable);

        assignBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        assignBtn.setText("Assign");
        assignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout assignmentsPageLayout = new javax.swing.GroupLayout(assignmentsPage);
        assignmentsPage.setLayout(assignmentsPageLayout);
        assignmentsPageLayout.setHorizontalGroup(
            assignmentsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assignmentsPageLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(assignmentsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(assignmentsPageLayout.createSequentialGroup()
                        .addGroup(assignmentsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(assignmentsPageLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(doctorNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86)
                        .addGroup(assignmentsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(assignmentsPageLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(doctorNameTf1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(assignmentsPageLayout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(assignBtn)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        assignmentsPageLayout.setVerticalGroup(
            assignmentsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assignmentsPageLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(assignmentsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(assignmentsPageLayout.createSequentialGroup()
                        .addGroup(assignmentsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorNameTf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(assignmentsPageLayout.createSequentialGroup()
                        .addGroup(assignmentsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(assignBtn)
                .addContainerGap(531, Short.MAX_VALUE))
        );

        pages.add(assignmentsPage, "assignmentsPage");

        assetsPage.setBackground(new java.awt.Color(255, 255, 255));

        assetNameTf.setBackground(new java.awt.Color(204, 204, 204));
        assetNameTf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        assetNameTf.setForeground(new java.awt.Color(0, 0, 0));
        assetNameTf.setText("Name");
        assetNameTf.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Search:");

        assetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Asset ID", "Name", "Type", "Status", "Capacity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        assetTable.getTableHeader().setReorderingAllowed(false);
        assetTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assetTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(assetTable);
        if (assetTable.getColumnModel().getColumnCount() > 0) {
            assetTable.getColumnModel().getColumn(0).setResizable(false);
            assetTable.getColumnModel().getColumn(1).setResizable(false);
            assetTable.getColumnModel().getColumn(2).setResizable(false);
            assetTable.getColumnModel().getColumn(3).setResizable(false);
            assetTable.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Selected Asset");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Asset:");
        jLabel6.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Status:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Capacity");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Department:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Operating From:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Operating To:");

        assetLbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        assetLbl.setForeground(new java.awt.Color(0, 0, 0));

        statusCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Closed", "Maintenance", "Renovation" }));

        departmentCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cardiology", "Radiology", "Pathology", "Emergency" }));

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout assetsPageLayout = new javax.swing.GroupLayout(assetsPage);
        assetsPage.setLayout(assetsPageLayout);
        assetsPageLayout.setHorizontalGroup(
            assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assetsPageLayout.createSequentialGroup()
                .addGroup(assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(assetsPageLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(assetNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(assetsPageLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel5))
                    .addGroup(assetsPageLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(assetsPageLayout.createSequentialGroup()
                                .addGroup(assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel7))
                                .addGap(27, 27, 27)
                                .addGroup(assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(statusCb, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(openingTf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                            .addComponent(closingTf, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGroup(assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(capacityTf, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(departmentCb, javax.swing.GroupLayout.Alignment.LEADING, 0, 130, Short.MAX_VALUE)))
                                    .addGroup(assetsPageLayout.createSequentialGroup()
                                        .addComponent(assetLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3))))
                            .addComponent(updateBtn)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(335, Short.MAX_VALUE))
        );
        assetsPageLayout.setVerticalGroup(
            assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assetsPageLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assetNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(assetLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(statusCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(capacityTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(departmentCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(openingTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(assetsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(closingTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(updateBtn)
                .addContainerGap(540, Short.MAX_VALUE))
        );

        pages.add(assetsPage, "assetsPage");

        ratesPage.setBackground(new java.awt.Color(255, 255, 255));

        rateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Rate ID", "Consultation Type", "Rate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        rateTable.getTableHeader().setReorderingAllowed(false);
        rateTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rateTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(rateTable);
        if (rateTable.getColumnModel().getColumnCount() > 0) {
            rateTable.getColumnModel().getColumn(0).setResizable(false);
            rateTable.getColumnModel().getColumn(1).setResizable(false);
            rateTable.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Selected Consultation");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Consultation:");
        jLabel14.setToolTipText("");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Base Rate (RM):");

        updateRateBtn.setText("Update");
        updateRateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRateBtnActionPerformed(evt);
            }
        });

        consultationLbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        consultationLbl.setForeground(new java.awt.Color(0, 0, 0));
        consultationLbl.setToolTipText("");

        javax.swing.GroupLayout ratesPageLayout = new javax.swing.GroupLayout(ratesPage);
        ratesPage.setLayout(ratesPageLayout);
        ratesPageLayout.setHorizontalGroup(
            ratesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ratesPageLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(ratesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ratesPageLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel13))
                    .addGroup(ratesPageLayout.createSequentialGroup()
                        .addGroup(ratesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ratesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(baseRateTf, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(consultationLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(updateRateBtn)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(328, Short.MAX_VALUE))
        );
        ratesPageLayout.setVerticalGroup(
            ratesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ratesPageLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(ratesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(consultationLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ratesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(baseRateTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(updateRateBtn)
                .addContainerGap(725, Short.MAX_VALUE))
        );

        pages.add(ratesPage, "ratesPage");

        insurancePage.setBackground(new java.awt.Color(255, 255, 255));

        insuranceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Insurance ID", "Insurance Name", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        insuranceTable.getTableHeader().setReorderingAllowed(false);
        insuranceTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insuranceTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(insuranceTable);
        if (insuranceTable.getColumnModel().getColumnCount() > 0) {
            insuranceTable.getColumnModel().getColumn(0).setResizable(false);
            insuranceTable.getColumnModel().getColumn(1).setResizable(false);
            insuranceTable.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Selected Insurance");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Insurance:");
        jLabel17.setToolTipText("");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Status:");

        updateInsuranceBtn.setText("Update");
        updateInsuranceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInsuranceBtnActionPerformed(evt);
            }
        });

        insuranceLbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        insuranceLbl.setForeground(new java.awt.Color(0, 0, 0));
        insuranceLbl.setToolTipText("");

        insuranceStatusCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Accepted", "Not Accepted" }));

        javax.swing.GroupLayout insurancePageLayout = new javax.swing.GroupLayout(insurancePage);
        insurancePage.setLayout(insurancePageLayout);
        insurancePageLayout.setHorizontalGroup(
            insurancePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insurancePageLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(insurancePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insurancePageLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel16))
                    .addGroup(insurancePageLayout.createSequentialGroup()
                        .addGroup(insurancePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(insurancePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(insuranceLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(insuranceStatusCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(updateInsuranceBtn)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(328, Short.MAX_VALUE))
        );
        insurancePageLayout.setVerticalGroup(
            insurancePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insurancePageLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(insurancePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(insuranceLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(insurancePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(insuranceStatusCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(updateInsuranceBtn)
                .addContainerGap(725, Short.MAX_VALUE))
        );

        pages.add(insurancePage, "insurancePage");

        profilePage.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout profilePageLayout = new javax.swing.GroupLayout(profilePage);
        profilePage.setLayout(profilePageLayout);
        profilePageLayout.setHorizontalGroup(
            profilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 887, Short.MAX_VALUE)
        );
        profilePageLayout.setVerticalGroup(
            profilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1083, Short.MAX_VALUE)
        );

        pages.add(profilePage, "profilePage");

        jSplitPane1.setRightComponent(pages);

        jPanel1.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1031, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1133, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setActiveButton(javax.swing.JButton activeButton) {
        javax.swing.JButton[] buttons = {dashboardBtn, usersBtn, assignmentsBtn, assetsBtn, ratesBtn, profileBtn, logoutBtn, insuranceBtn};
        
        for (javax.swing.JButton btn : buttons) {
            btn.setContentAreaFilled(false);
            btn.setOpaque(false);
            btn.setBorderPainted(false);
            btn.setFocusPainted(false);
            btn.setBackground(new java.awt.Color(102, 204, 255));
            btn.setForeground(Color.black);
        }
        
        activeButton.setContentAreaFilled(false);
        activeButton.setOpaque(true);
        activeButton.setBorderPainted(false);
        activeButton.setFocusPainted(false);
//        activeButton.setBackground(new java.awt.Color(70, 100, 220));
        activeButton.setBackground(Color.white);
        activeButton.setForeground(Color.black);
    }
    
    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        cardLayout.show(pages, "dashboardPage");
        setActiveButton(dashboardBtn);
        
        loadDashboardDetails();
    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void usersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersBtnActionPerformed
        cardLayout.show(pages, "usersPage");
        setActiveButton(usersBtn);
        
        loadUserTable();
    }//GEN-LAST:event_usersBtnActionPerformed

    private void assignmentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignmentsBtnActionPerformed
        cardLayout.show(pages, "assignmentsPage");
        setActiveButton(assignmentsBtn);
    }//GEN-LAST:event_assignmentsBtnActionPerformed

    private void assetsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assetsBtnActionPerformed
        cardLayout.show(pages, "assetsPage");
        setActiveButton(assetsBtn);
        
        loadAssetTable();
    }//GEN-LAST:event_assetsBtnActionPerformed

    private void ratesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratesBtnActionPerformed
        cardLayout.show(pages, "ratesPage");
        setActiveButton(ratesBtn);
        
        loadRateTable();
    }//GEN-LAST:event_ratesBtnActionPerformed

    private void profileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnActionPerformed
        cardLayout.show(pages, "profilePage");
        setActiveButton(profileBtn);
//        ChangePasswordDialog cpd = new ChangePasswordDialog(this,true);
//        cpd.setLocationRelativeTo(this);
//        cpd.setVisible(true);
    }//GEN-LAST:event_profileBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        setActiveButton(logoutBtn);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void insuranceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceBtnActionPerformed
        cardLayout.show(pages, "insurancePage");
        setActiveButton(insuranceBtn);
        
        loadInsuranceTable();
    }//GEN-LAST:event_insuranceBtnActionPerformed

    private AdminService adminService = new AdminService();
    
    private void loadDashboardDetails() {
        int totalUsers = 0;
        int doctorCount = 0;
        int managerCount = 0;
        int patientCount = 0;
        
        for (User user : adminService.getAllUsers()) {
            totalUsers++;
            
            if (user.getRole().equalsIgnoreCase("Doctor")) {
                doctorCount++;
            } else if (user.getRole().equalsIgnoreCase("MedicalManager")) {
                managerCount++;
            } else if (user.getRole().equalsIgnoreCase("Patient")) {
                patientCount++;
            }
        }
        
        totalUserLbl.setText(totalUsers + "");
        totalDoctorLbl.setText(doctorCount + "");
        totalManagerLbl.setText(managerCount + "");
        totalPatientLbl.setText(patientCount + "");
    }
    
    private String selectedUserId = null;
    
    private void loadUserTable() {
        DefaultTableModel model = (DefaultTableModel)userTable.getModel();
        
        model.setRowCount(0);
        
        for (User user : adminService.getAllUsers()) {
            model.addRow(new Object[]{user.getUserId(), user.getName(), user.getEmail(), user.getPhone(), user.getGender(), user.getRole()});
        }
    }
    
    // Manage and allocate assets
    FileAssetRepo assetRepo = new FileAssetRepo();
    AssetService assetService = new AssetService();
    String selectedAssetId;
    private TableRowSorter<DefaultTableModel> assetSorter;
    
    private void loadAssetTable() {
        DefaultTableModel model = (DefaultTableModel)assetTable.getModel();
        
        model.setRowCount(0);
        
        for (HospitalAsset asset : assetRepo.getAllAssets()) {
            model.addRow(new Object[]{asset.getAssetId(), asset.getAssetName(), asset.getAssetType(), asset.getStatus(), asset.getCapacity()});
        }
    }
    
    private void setupAssetFilter() {
        DefaultTableModel model = (DefaultTableModel)assetTable.getModel();
        
        assetSorter = new TableRowSorter<>(model);
        assetTable.setRowSorter(assetSorter);
        
        assetNameTf.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filterAssets();
            }
            
            @Override
            public void removeUpdate(DocumentEvent e) {
                filterAssets();
            }
            
            @Override
            public void changedUpdate(DocumentEvent e) {
                filterAssets();
            }
        });
    }
    
    public void filterAssets() {
        String text = assetNameTf.getText().trim();
        
        if (text.isEmpty()) {
            assetSorter.setRowFilter(null);
        } else {
            assetSorter.setRowFilter(RowFilter.regexFilter("(?i)" + Pattern.quote(text), 1));
        }
    }
    
    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        String status = statusCb.getSelectedItem().toString();
        String departmentId = departmentCb.getSelectedItem().toString();
        String openingTime = openingTf.getText().trim();
        String closingTime = closingTf.getText().trim();
        int capacity = Integer.parseInt(capacityTf.getText().trim());
        
        if (assetService.validation(selectedAssetId, status, departmentId, openingTime, closingTime, capacity)) {
            try {
                boolean updated = assetRepo.updateAsset(selectedAssetId, status, departmentId, openingTime, closingTime, capacity);
            
                if (updated) {
                    JOptionPane.showMessageDialog(this, "Asset updated successfully.");

                    loadAssetTable();
                }
            } catch (IllegalArgumentException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void assetTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assetTableMouseClicked
        int selectedRow = assetTable.getSelectedRow();
        int modelRow = assetTable.convertRowIndexToModel(selectedRow);
        selectedAssetId = assetTable.getModel().getValueAt(modelRow, 0).toString();
        HospitalAsset asset = assetRepo.findByAssetId(selectedAssetId);

        if (asset != null) {
            assetLbl.setText(asset.getAssetName());
            statusCb.setSelectedItem(asset.getStatus());
            departmentCb.setSelectedItem(asset.getDepartmentId());
            openingTf.setText(asset.getOpeningTime());
            closingTf.setText(asset.getClosingTime());
            capacityTf.setText(String.valueOf(asset.getCapacity()));
        }
    }//GEN-LAST:event_assetTableMouseClicked

    // Base consultation rates and insurance networks
    private ConfigurationService configurationService = new ConfigurationService();
    private String selectedRateId = null;
    private String selectedInsuranceId = null;
    
    private void loadRateTable() {
        DefaultTableModel model = (DefaultTableModel)rateTable.getModel();
        
        model.setRowCount(0);
        
        for (ConsultationRate rate : configurationService.getAllRates()) {
            model.addRow(new Object[]{rate.getRateId(), rate.getConsultationType(), String.format("%.2f", rate.getBaseRate())});
        }
    }
    
    private void rateTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rateTableMouseClicked
        int row = rateTable.getSelectedRow();
        
        if (row == -1) {
            return;
        }
        
        int modelRow = rateTable.convertRowIndexToModel(row);
        selectedRateId = rateTable.getModel().getValueAt(modelRow, 0).toString();
        ConsultationRate rate = configurationService.findByRateId(selectedRateId);
        
        if (rate != null) {
            consultationLbl.setText(rate.getConsultationType());
            
            baseRateTf.setText(String.format("%.2f", rate.getBaseRate()));
        }
    }//GEN-LAST:event_rateTableMouseClicked
    
    private void updateRateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRateBtnActionPerformed
        if (selectedRateId == null) {
            JOptionPane.showMessageDialog(this, "Please select a consultation type.");
            return;
        }
        
        try {
            boolean updated = configurationService.updateRate(selectedRateId, baseRateTf.getText());
            
            if (updated) {
                JOptionPane.showMessageDialog(this, "Consultation rate updated successfully.");
            }
            
            loadRateTable();
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_updateRateBtnActionPerformed

    private void loadInsuranceTable() {
        DefaultTableModel model = (DefaultTableModel)insuranceTable.getModel();
        
        model.setRowCount(0);
        
        for (InsuranceNetwork insurance : configurationService.getAllInsurance()) {
            model.addRow(new Object[]{insurance.getInsuranceId(), insurance.getInsuranceName(), insurance.getStatus()});
        }
    }
    
    private void insuranceTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insuranceTableMouseClicked
        int row = insuranceTable.getSelectedRow();
        
        if (row == -1) {
            return;
        }
        
        int modelRow = insuranceTable.convertRowIndexToModel(row);
        selectedInsuranceId = insuranceTable.getModel().getValueAt(modelRow, 0).toString();
        InsuranceNetwork insurance = configurationService.findByInsuranceId(selectedInsuranceId);
        
        if (insurance != null) {
            insuranceLbl.setText(insurance.getInsuranceName());
            
            insuranceStatusCb.setSelectedItem(insurance.getStatus());
        }
    }//GEN-LAST:event_insuranceTableMouseClicked

    private void updateInsuranceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInsuranceBtnActionPerformed
        if (selectedInsuranceId == null) {
            JOptionPane.showMessageDialog(this, "Please select an insurance network.");
            return;
        }
        
        String status = insuranceStatusCb.getSelectedItem().toString();
        
        try {
            boolean updated = configurationService.updateInsurance(selectedInsuranceId, status);
            
            if (updated) {
                JOptionPane.showMessageDialog(this, "Insurance network updated successfully.");
                
                loadInsuranceTable();
            }
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_updateInsuranceBtnActionPerformed

    private void userTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseClicked
        int selectedRow = userTable.getSelectedRow();
        
        if (selectedRow == -1) {
            return;
        }
        
        int modelRow = userTable.convertRowIndexToModel(selectedRow);
        selectedUserId = userTable.getModel().getValueAt(modelRow, 0).toString();
        User user = adminService.findByUserId(selectedUserId);
        
        if (user == null) {
            return;
        }
        
        userIdLbl.setText(user.getUserId());
        usernameTf.setText(user.getName());
        emailTf.setText(user.getEmail());
        phoneTf.setText(user.getPhone());
        genderCb.setSelectedItem(user.getGender());
        roleCb.setSelectedItem(user.getRole());
    }//GEN-LAST:event_userTableMouseClicked

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        String name = usernameTf.getText().trim();
        String email = emailTf.getText().trim();
        String password = "123";
        String phone = phoneTf.getText().trim();
        String gender = genderCb.getSelectedItem().toString();
        String role = roleCb.getSelectedItem().toString();
        
        try {
            boolean created = adminService.createUser(name, email, password, phone, gender, role);
            
            if (created) {
                JOptionPane.showMessageDialog(this, "User created successfully.\nDefault password: 123");
                loadUserTable();
                clearUserForm();
                loadDashboardDetails(); 
            }
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_createBtnActionPerformed

    private void updateUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateUserBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateUserBtnActionPerformed

    private void deleteUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserBtnActionPerformed
        if (selectedUserId == null) {
            JOptionPane.showMessageDialog(this, "Please select a user.");
            return;
        }


        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this user?", "Delete User", JOptionPane.YES_NO_OPTION);


        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        boolean deleted = adminService.deleteUser(selectedUserId);

        if (deleted) {
            JOptionPane.showMessageDialog(this, "User deleted successfully.");
            loadUserTable();
            clearUserForm();
            loadDashboardDetails();
        }
    }//GEN-LAST:event_deleteUserBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        clearUserForm();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void assignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBtnActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_assignBtnActionPerformed
    
    private void clearUserForm() {
        selectedUserId = null;
        
        userIdLbl.setText("");
        usernameTf.setText("");
        emailTf.setText("");
        phoneTf.setText("");
        genderCb.setSelectedIndex(0);
        roleCb.setSelectedIndex(0);
        
        userTable.clearSelection();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {          
                new Admin_Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel assetLbl;
    private javax.swing.JTextField assetNameTf;
    private javax.swing.JTable assetTable;
    private javax.swing.JButton assetsBtn;
    private javax.swing.JPanel assetsPage;
    private javax.swing.JButton assignBtn;
    private javax.swing.JButton assignmentsBtn;
    private javax.swing.JPanel assignmentsPage;
    private javax.swing.JTextField baseRateTf;
    private javax.swing.JTextField capacityTf;
    private javax.swing.JButton clearBtn;
    private javax.swing.JTextField closingTf;
    private javax.swing.JLabel consultationLbl;
    private javax.swing.JButton createBtn;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JPanel dashboardPage;
    private javax.swing.JButton deleteUserBtn;
    private javax.swing.JComboBox<String> departmentCb;
    private javax.swing.JTextField doctorNameTf;
    private javax.swing.JTextField doctorNameTf1;
    private javax.swing.JTable doctorTable;
    private javax.swing.JTextField emailTf;
    private javax.swing.JComboBox<String> genderCb;
    private javax.swing.JButton insuranceBtn;
    private javax.swing.JLabel insuranceLbl;
    private javax.swing.JPanel insurancePage;
    private javax.swing.JComboBox<String> insuranceStatusCb;
    private javax.swing.JTable insuranceTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTable managerTable;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTextField openingTf;
    private javax.swing.JPanel pages;
    private javax.swing.JTextField phoneTf;
    private javax.swing.JButton profileBtn;
    private javax.swing.JPanel profilePage;
    private javax.swing.JTable rateTable;
    private javax.swing.JButton ratesBtn;
    private javax.swing.JPanel ratesPage;
    private javax.swing.JComboBox<String> roleCb;
    private javax.swing.JPanel sidebar;
    private javax.swing.JComboBox<String> statusCb;
    private javax.swing.JLabel totalDoctorLbl;
    private javax.swing.JLabel totalManagerLbl;
    private javax.swing.JLabel totalPatientLbl;
    private javax.swing.JLabel totalUserLbl;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton updateInsuranceBtn;
    private javax.swing.JButton updateRateBtn;
    private javax.swing.JButton updateUserBtn;
    private javax.swing.JLabel userIdLbl;
    private javax.swing.JTable userTable;
    private javax.swing.JTextField usernameTf;
    private javax.swing.JButton usersBtn;
    private javax.swing.JPanel usersPage;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
