/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import java.awt.CardLayout;
import java.awt.Color;
import model.Doctor;
import model.User;

/**
 *
 * @author xuanchen
 */
public class Doctor_Dashboard extends javax.swing.JFrame {

    private User user;
    private Doctor doctor;
    CardLayout cardLayout;
    
    public Doctor_Dashboard(User user, Doctor doctor) {
        initComponents();
        
        this.user = user;
        welcomeLbl.setText("Welcome " + user.getName());
        cardLayout = (CardLayout)pages.getLayout();
        
        cardLayout.show(pages, "dashboardPage");
        setActiveButton(dashboardBtn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        sidebar = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        dashboardBtn = new javax.swing.JButton();
        patientsBtn = new javax.swing.JButton();
        consultationsBtn = new javax.swing.JButton();
        prescriptionsBtn = new javax.swing.JButton();
        requestsBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        profileBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        pages = new javax.swing.JPanel();
        dashboardPage = new javax.swing.JPanel();
        patientsPage = new javax.swing.JPanel();
        consultationsPage = new javax.swing.JPanel();
        prescriptionsPage = new javax.swing.JPanel();
        requestsPage = new javax.swing.JPanel();
        profilePage = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        userIdTF = new javax.swing.JTextField();
        editBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        nameTF = new javax.swing.JTextField();
        emailTF = new javax.swing.JTextField();
        phoneTF = new javax.swing.JTextField();
        genderTF = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(740, 160));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Hospital Management Sytem");

        welcomeLbl.setFont(new java.awt.Font("Heiti TC", 1, 12)); // NOI18N
        welcomeLbl.setForeground(new java.awt.Color(0, 0, 0));
        welcomeLbl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        welcomeLbl.setText("Welcome");
        welcomeLbl.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(welcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(welcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.NORTH);

        jSplitPane1.setDividerLocation(195);
        jSplitPane1.setDividerSize(0);

        sidebar.setBackground(new java.awt.Color(102, 204, 255));
        sidebar.setMaximumSize(new java.awt.Dimension(200, 500));
        sidebar.setPreferredSize(new java.awt.Dimension(200, 478));
        sidebar.setLayout(new java.awt.BorderLayout());

        menuPanel.setBackground(new java.awt.Color(102, 204, 255));
        menuPanel.setPreferredSize(new java.awt.Dimension(185, 500));
        menuPanel.setLayout(new java.awt.GridLayout(10, 1, 0, 5));

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(50, 80));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 195, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        menuPanel.add(jPanel2);

        dashboardBtn.setBackground(new java.awt.Color(51, 51, 255));
        dashboardBtn.setFont(new java.awt.Font("Menlo", 0, 14)); // NOI18N
        dashboardBtn.setForeground(new java.awt.Color(0, 0, 0));
        dashboardBtn.setText("Dashboard");
        dashboardBtn.setAutoscrolls(true);
        dashboardBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        dashboardBtn.setBorderPainted(false);
        dashboardBtn.setContentAreaFilled(false);
        dashboardBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboardBtn.setFocusPainted(false);
        dashboardBtn.setFocusable(false);
        dashboardBtn.setMargin(new java.awt.Insets(0, 15, 0, 15));
        dashboardBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });
        menuPanel.add(dashboardBtn);

        patientsBtn.setFont(new java.awt.Font("Menlo", 0, 14)); // NOI18N
        patientsBtn.setForeground(new java.awt.Color(0, 0, 0));
        patientsBtn.setText("Patients");
        patientsBtn.setAutoscrolls(true);
        patientsBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        patientsBtn.setBorderPainted(false);
        patientsBtn.setContentAreaFilled(false);
        patientsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        patientsBtn.setFocusPainted(false);
        patientsBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        patientsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientsBtnActionPerformed(evt);
            }
        });
        menuPanel.add(patientsBtn);

        consultationsBtn.setFont(new java.awt.Font("Menlo", 0, 14)); // NOI18N
        consultationsBtn.setForeground(new java.awt.Color(0, 0, 0));
        consultationsBtn.setText("Consultations");
        consultationsBtn.setAutoscrolls(true);
        consultationsBtn.setBorder(null);
        consultationsBtn.setBorderPainted(false);
        consultationsBtn.setContentAreaFilled(false);
        consultationsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultationsBtn.setFocusPainted(false);
        consultationsBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        consultationsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultationsBtnActionPerformed(evt);
            }
        });
        menuPanel.add(consultationsBtn);

        prescriptionsBtn.setFont(new java.awt.Font("Menlo", 0, 14)); // NOI18N
        prescriptionsBtn.setForeground(new java.awt.Color(0, 0, 0));
        prescriptionsBtn.setText("Prescriptions");
        prescriptionsBtn.setAutoscrolls(true);
        prescriptionsBtn.setBorder(null);
        prescriptionsBtn.setBorderPainted(false);
        prescriptionsBtn.setContentAreaFilled(false);
        prescriptionsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prescriptionsBtn.setFocusPainted(false);
        prescriptionsBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        prescriptionsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prescriptionsBtnActionPerformed(evt);
            }
        });
        menuPanel.add(prescriptionsBtn);

        requestsBtn.setFont(new java.awt.Font("Menlo", 0, 14)); // NOI18N
        requestsBtn.setForeground(new java.awt.Color(0, 0, 0));
        requestsBtn.setText("Requests");
        requestsBtn.setAutoscrolls(true);
        requestsBtn.setBorder(null);
        requestsBtn.setBorderPainted(false);
        requestsBtn.setContentAreaFilled(false);
        requestsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        requestsBtn.setFocusPainted(false);
        requestsBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        requestsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestsBtnActionPerformed(evt);
            }
        });
        menuPanel.add(requestsBtn);

        jPanel4.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 195, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        menuPanel.add(jPanel4);

        jPanel7.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 195, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        menuPanel.add(jPanel7);

        profileBtn.setFont(new java.awt.Font("Menlo", 0, 14)); // NOI18N
        profileBtn.setForeground(new java.awt.Color(0, 0, 0));
        profileBtn.setText("Profile");
        profileBtn.setAutoscrolls(true);
        profileBtn.setBorder(null);
        profileBtn.setBorderPainted(false);
        profileBtn.setContentAreaFilled(false);
        profileBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profileBtn.setFocusPainted(false);
        profileBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnActionPerformed(evt);
            }
        });
        menuPanel.add(profileBtn);

        logoutBtn.setFont(new java.awt.Font("Menlo", 0, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(0, 0, 0));
        logoutBtn.setText("Logout");
        logoutBtn.setAutoscrolls(true);
        logoutBtn.setBorder(null);
        logoutBtn.setBorderPainted(false);
        logoutBtn.setContentAreaFilled(false);
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.setFocusPainted(false);
        logoutBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        menuPanel.add(logoutBtn);

        sidebar.add(menuPanel, java.awt.BorderLayout.NORTH);

        jSplitPane1.setLeftComponent(sidebar);

        pages.setLayout(new java.awt.CardLayout());

        dashboardPage.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout dashboardPageLayout = new javax.swing.GroupLayout(dashboardPage);
        dashboardPage.setLayout(dashboardPageLayout);
        dashboardPageLayout.setHorizontalGroup(
            dashboardPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        dashboardPageLayout.setVerticalGroup(
            dashboardPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1083, Short.MAX_VALUE)
        );

        pages.add(dashboardPage, "dashboardPage");

        patientsPage.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout patientsPageLayout = new javax.swing.GroupLayout(patientsPage);
        patientsPage.setLayout(patientsPageLayout);
        patientsPageLayout.setHorizontalGroup(
            patientsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        patientsPageLayout.setVerticalGroup(
            patientsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1083, Short.MAX_VALUE)
        );

        pages.add(patientsPage, "patientsPage");

        consultationsPage.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout consultationsPageLayout = new javax.swing.GroupLayout(consultationsPage);
        consultationsPage.setLayout(consultationsPageLayout);
        consultationsPageLayout.setHorizontalGroup(
            consultationsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        consultationsPageLayout.setVerticalGroup(
            consultationsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1083, Short.MAX_VALUE)
        );

        pages.add(consultationsPage, "consultationsPage");

        prescriptionsPage.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout prescriptionsPageLayout = new javax.swing.GroupLayout(prescriptionsPage);
        prescriptionsPage.setLayout(prescriptionsPageLayout);
        prescriptionsPageLayout.setHorizontalGroup(
            prescriptionsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        prescriptionsPageLayout.setVerticalGroup(
            prescriptionsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1083, Short.MAX_VALUE)
        );

        pages.add(prescriptionsPage, "prescriptionsPage");

        requestsPage.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout requestsPageLayout = new javax.swing.GroupLayout(requestsPage);
        requestsPage.setLayout(requestsPageLayout);
        requestsPageLayout.setHorizontalGroup(
            requestsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        requestsPageLayout.setVerticalGroup(
            requestsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1083, Short.MAX_VALUE)
        );

        pages.add(requestsPage, "requestsPage");

        profilePage.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("User ID:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Phone:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Gender:");

        userIdTF.setBackground(new java.awt.Color(255, 255, 255));
        userIdTF.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        userIdTF.setForeground(new java.awt.Color(0, 0, 0));
        userIdTF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(51, 153, 255)));
        userIdTF.setEnabled(false);

        editBtn.setBackground(new java.awt.Color(0, 153, 255));
        editBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        editBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBtn.setText("Edit Profile");
        editBtn.setBorderPainted(false);
        editBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editBtn.setFocusPainted(false);
        editBtn.setPreferredSize(new java.awt.Dimension(140, 40));
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Change Password");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setPreferredSize(new java.awt.Dimension(160, 40));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        nameTF.setBackground(new java.awt.Color(255, 255, 255));
        nameTF.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        nameTF.setForeground(new java.awt.Color(0, 0, 0));
        nameTF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(51, 153, 255)));
        nameTF.setEnabled(false);

        emailTF.setBackground(new java.awt.Color(255, 255, 255));
        emailTF.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        emailTF.setForeground(new java.awt.Color(0, 0, 0));
        emailTF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(51, 153, 255)));
        emailTF.setEnabled(false);

        phoneTF.setBackground(new java.awt.Color(255, 255, 255));
        phoneTF.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        phoneTF.setForeground(new java.awt.Color(0, 0, 0));
        phoneTF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(51, 153, 255)));
        phoneTF.setEnabled(false);

        genderTF.setBackground(new java.awt.Color(255, 255, 255));
        genderTF.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        genderTF.setForeground(new java.awt.Color(0, 0, 0));
        genderTF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(51, 153, 255)));
        genderTF.setEnabled(false);

        saveBtn.setBackground(new java.awt.Color(0, 204, 0));
        saveBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("SAVE");
        saveBtn.setBorderPainted(false);
        saveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveBtn.setFocusPainted(false);
        saveBtn.setPreferredSize(new java.awt.Dimension(140, 40));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(204, 0, 51));
        cancelBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("CANCEL");
        cancelBtn.setBorderPainted(false);
        cancelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelBtn.setFocusPainted(false);
        cancelBtn.setPreferredSize(new java.awt.Dimension(140, 40));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profilePageLayout = new javax.swing.GroupLayout(profilePage);
        profilePage.setLayout(profilePageLayout);
        profilePageLayout.setHorizontalGroup(
            profilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePageLayout.createSequentialGroup()
                .addGroup(profilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePageLayout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addGroup(profilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(profilePageLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(profilePageLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(profilePageLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(userIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(profilePageLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(profilePageLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(genderTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(profilePageLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(profilePageLayout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        profilePageLayout.setVerticalGroup(
            profilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePageLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(profilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(userIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(profilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(profilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(profilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(profilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(genderTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(profilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(620, Short.MAX_VALUE))
        );

        pages.add(profilePage, "profilePage");

        jSplitPane1.setRightComponent(pages);

        jPanel1.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1031, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1133, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setActiveButton(javax.swing.JButton activeButton) {
        javax.swing.JButton[] buttons = {dashboardBtn, patientsBtn, consultationsBtn, prescriptionsBtn, requestsBtn, profileBtn, logoutBtn};
        
        for (javax.swing.JButton btn : buttons) {
            btn.setContentAreaFilled(false);
            btn.setOpaque(false);
            btn.setBorderPainted(false);
            btn.setFocusPainted(false);
            btn.setBackground(new java.awt.Color(102, 204, 255));
            btn.setForeground(Color.black);
        }
        
        activeButton.setContentAreaFilled(false);
        activeButton.setOpaque(true);
        activeButton.setBorderPainted(false);
        activeButton.setFocusPainted(false);
//        activeButton.setBackground(new java.awt.Color(70, 100, 220));
        activeButton.setBackground(Color.white);
        activeButton.setForeground(Color.black);
    }
    
    private void setProfile() {
        userIdTF.setText(user.getUserId());
        nameTF.setText(user.getName());
        emailTF.setText(user.getEmail());
        phoneTF.setText(user.getPhone());
        genderTF.setText(user.getGender());
    }
    
    private void enableTextField(boolean b) {
        if (b) {
            nameTF.setEnabled(true);
            emailTF.setEnabled(true);
            phoneTF.setEnabled(true);
            genderTF.setEnabled(true);
        } else {
            nameTF.setEnabled(false);
            emailTF.setEnabled(false);
            phoneTF.setEnabled(false);
            genderTF.setEnabled(false);
        }
    }
    
    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        cardLayout.show(pages, "dashboardPage");
        setActiveButton(dashboardBtn);
        
    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void patientsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientsBtnActionPerformed
        cardLayout.show(pages, "patientsPage");
        setActiveButton(patientsBtn);
    }//GEN-LAST:event_patientsBtnActionPerformed

    private void consultationsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultationsBtnActionPerformed
        cardLayout.show(pages, "consultationsPage");
        setActiveButton(consultationsBtn);
    }//GEN-LAST:event_consultationsBtnActionPerformed

    private void prescriptionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prescriptionsBtnActionPerformed
        cardLayout.show(pages, "prescriptionsPage");
        setActiveButton(prescriptionsBtn);
    }//GEN-LAST:event_prescriptionsBtnActionPerformed

    private void requestsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestsBtnActionPerformed
        cardLayout.show(pages, "requestsPage");
        setActiveButton(requestsBtn);
    }//GEN-LAST:event_requestsBtnActionPerformed

    private void profileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnActionPerformed
        cardLayout.show(pages, "profilePage");
        setActiveButton(profileBtn);
        
        setProfile();
        
//        ChangePasswordDialog cpd = new ChangePasswordDialog(this,true);
//        cpd.setLocationRelativeTo(this);
//        cpd.setVisible(true);
    }//GEN-LAST:event_profileBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        setActiveButton(logoutBtn);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        enableTextField(true);
    }//GEN-LAST:event_editBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        setProfile();
        enableTextField(false);
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                User testUser = new User("Uid001", "Test Doctor", "doctor@gmail.com", "123", "01234556", "Male", "doctor");
                Doctor testDoctor = new Doctor("D001", "Uid001", "ciroprator", "MM001");
                
                new Doctor_Dashboard(testUser, testDoctor).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton consultationsBtn;
    private javax.swing.JPanel consultationsPage;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JPanel dashboardPage;
    private javax.swing.JButton editBtn;
    private javax.swing.JTextField emailTF;
    private javax.swing.JTextField genderTF;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTextField nameTF;
    private javax.swing.JPanel pages;
    private javax.swing.JButton patientsBtn;
    private javax.swing.JPanel patientsPage;
    private javax.swing.JTextField phoneTF;
    private javax.swing.JButton prescriptionsBtn;
    private javax.swing.JPanel prescriptionsPage;
    private javax.swing.JButton profileBtn;
    private javax.swing.JPanel profilePage;
    private javax.swing.JButton requestsBtn;
    private javax.swing.JPanel requestsPage;
    private javax.swing.JButton saveBtn;
    private javax.swing.JPanel sidebar;
    private javax.swing.JTextField userIdTF;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
