package medManager;


import frontend.Hospital_Login;
import javax.swing.JOptionPane;
import medManager.GUIManageDoctors;
import medManager.GUIManageAssessmentType;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ryne
 */
public class GUIManagerMenu extends javax.swing.JFrame {
//    MedicalManager manager = new MedicalManager("M001");
    MedicalManager manager;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIManagerMenu.class.getName());

    /**
     * Creates new form ManagerMenu
     */
    public GUIManagerMenu() {
        initComponents();
    }
    
    public GUIManagerMenu(MedicalManager manager) {
        initComponents();
        this.manager = manager;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnDoctors = new javax.swing.JButton();
        btnDepts = new javax.swing.JButton();
        btnShifts = new javax.swing.JButton();
        btnViewSummaries = new javax.swing.JButton();
        btnViewMetrics = new javax.swing.JButton();
        btnAssessmentTypes = new javax.swing.JButton();
        btnAssessmentTypes1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setText("Medical Manager Menu");

        btnDoctors.setText("Manage Doctors");
        btnDoctors.addActionListener(this::btnDoctorsActionPerformed);

        btnDepts.setText("Manage Departments");
        btnDepts.addActionListener(this::btnDeptsActionPerformed);

        btnShifts.setText("Manage Shifts");
        btnShifts.addActionListener(this::btnShiftsActionPerformed);

        btnViewSummaries.setText("View Revenue Summaries");
        btnViewSummaries.addActionListener(this::btnViewSummariesActionPerformed);

        btnViewMetrics.setText("View Hospital Metrics");
        btnViewMetrics.addActionListener(this::btnViewMetricsActionPerformed);

        btnAssessmentTypes.setText("Manage Assessment Types");
        btnAssessmentTypes.addActionListener(this::btnAssessmentTypesActionPerformed);

        btnAssessmentTypes1.setText("Logout");
        btnAssessmentTypes1.addActionListener(this::btnAssessmentTypes1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnViewSummaries, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnShifts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDepts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDoctors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewMetrics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAssessmentTypes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAssessmentTypes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(btnDoctors)
                .addGap(18, 18, 18)
                .addComponent(btnDepts)
                .addGap(18, 18, 18)
                .addComponent(btnShifts)
                .addGap(18, 18, 18)
                .addComponent(btnViewSummaries)
                .addGap(18, 18, 18)
                .addComponent(btnViewMetrics)
                .addGap(18, 18, 18)
                .addComponent(btnAssessmentTypes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnAssessmentTypes1)
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeptsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new GUIManageDepartments(manager).setVisible(true);
    }//GEN-LAST:event_btnDeptsActionPerformed

    private void btnShiftsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShiftsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new GUIManageShifts(manager).setVisible(true);
    }//GEN-LAST:event_btnShiftsActionPerformed

    private void btnViewSummariesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSummariesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new GUIViewRevenueSummary(manager).setVisible(true);
    }//GEN-LAST:event_btnViewSummariesActionPerformed

    private void btnViewMetricsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMetricsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new GUIViewHospitalMetrics(manager).setVisible(true);
    }//GEN-LAST:event_btnViewMetricsActionPerformed

    private void btnAssessmentTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssessmentTypesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new GUIManageAssessmentType(manager).setVisible(true);
    }//GEN-LAST:event_btnAssessmentTypesActionPerformed

    private void btnDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new GUIManageDoctors(manager).setVisible(true);
    }//GEN-LAST:event_btnDoctorsActionPerformed

    private void btnAssessmentTypes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssessmentTypes1ActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, "Confirm to logout?", "Confirm Logout", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (choice == JOptionPane.YES_OPTION) {
            Hospital_Login login = new Hospital_Login();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnAssessmentTypes1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIManagerMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssessmentTypes;
    private javax.swing.JButton btnAssessmentTypes1;
    private javax.swing.JButton btnDepts;
    private javax.swing.JButton btnDoctors;
    private javax.swing.JButton btnShifts;
    private javax.swing.JButton btnViewMetrics;
    private javax.swing.JButton btnViewSummaries;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
