package medManager;


import java.io.*;
import java.text.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.*;
import javax.swing.text.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ryne
 */
public class GUIManageAssessmentType extends javax.swing.JFrame {
    private MedicalManager manager;
    private DefaultTableModel model = new DefaultTableModel();
    private String[] columns = {"Assessment Type ID", "Assessment Type Name", "Description"};
    int row = -1;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIManageAssessmentType.class.getName());

    /**
     * Creates new form GUIManageAssessmentType
     */
    public GUIManageAssessmentType() {
        initComponents();
    }
    
    public GUIManageAssessmentType(MedicalManager manager) {
        initComponents();
        this.manager = manager;
        model.setColumnIdentifiers(columns);
        loadTable();
        txtId.requestFocusInWindow();
        
        // fix input for txtShiftId
        try {
            MaskFormatter idMask = new MaskFormatter("'A###");
            txtId.setFormatterFactory(new DefaultFormatterFactory(idMask));
        } catch (ParseException e) {
            // only triggered when mask format failed
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtDesc = new javax.swing.JTextField();
        txtId = new javax.swing.JFormattedTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        assessmentTable = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setText("Manage Assessment Type");

        jLabel2.setText("Assessment Type ID: ");

        jLabel3.setText("Assessment Name: ");

        jLabel4.setText("Description: ");

        btnAdd.setText("Add New Assessment Type");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setText("Update Assessment Type");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnRemove.setText("Remove Assessment Type");
        btnRemove.addActionListener(this::btnRemoveActionPerformed);

        assessmentTable.setModel(model);
        assessmentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assessmentTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(assessmentTable);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        btnClear.setText("Clear Selection");
        btnClear.addActionListener(this::btnClearActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                                    .addComponent(txtName)
                                    .addComponent(txtId)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnBack)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnClear))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnAdd)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnUpdate)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnRemove)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel1)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnRemove))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnClear))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadTable(){
        model.setRowCount(0);
        
        try{
            FileReader fr = new FileReader("data/assessmentType.txt");
            BufferedReader br = new BufferedReader(fr);
            
            String line = null;
            String[] items;
            
            while((line = br.readLine()) != null){
                items = line.split(", ");
                model.addRow(items);
            }
            
            fr.close();
            br.close();
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public boolean ifIdExist(String checkId){
        for(int row = 0; row < assessmentTable.getRowCount(); row++){
            String id = assessmentTable.getValueAt(row, 0).toString().trim();
            if (id.equals(checkId)){
                return true;
            }
        }
        return false;
    }
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new GUIManagerMenu(manager).setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        assessmentTable.clearSelection();
        txtId.setEditable(true);
        txtId.setText(null);
        txtName.setText("");
        txtDesc.setText("");
        txtId.requestFocusInWindow();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String id = String.format(txtId.getText()).trim();
        String name = String.format(txtName.getText()).trim();
        String desc = String.format(txtDesc.getText()).trim();
        
        if(id.isEmpty() || name.isEmpty() || desc.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill in all field", "Empty Values", JOptionPane.WARNING_MESSAGE);
            return;
        }else if(ifIdExist(id)){
            JOptionPane.showMessageDialog(null, "Assessment type ID is duplicated", "Duplicated Department ID", JOptionPane.WARNING_MESSAGE);
            return;
        }else{
            try{
                FileWriter fw = new FileWriter("data/assessmentType.txt", true);
                BufferedWriter bw = new BufferedWriter(fw);

                bw.write(String.format("%s, %s, %s", id, name, desc));
                bw.newLine();

                bw.close();
                fw.close();
            }catch(IOException e){
                JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
            }
            JOptionPane.showMessageDialog(null, String.format("New assessment type: %s is added successfully", name), "Success", JOptionPane.INFORMATION_MESSAGE);
            loadTable();
            txtId.setText("");
            txtName.setText("");
            txtDesc.setText("");
            
            txtId.setEditable(true);
            txtId.requestFocusInWindow();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String id = String.format(txtId.getText()).trim();
        String newName = String.format(txtName.getText()).trim();
        String newDesc = String.format(txtDesc.getText()).trim();
        
        row = assessmentTable.getSelectedRow();
        
        if(row == -1){
            JOptionPane.showMessageDialog(null, "Please select a row to edit", "Empty Values", JOptionPane.WARNING_MESSAGE);
            return;
        }else if(id.isEmpty() || newName.isEmpty() || newDesc.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill in all field", "Empty Values", JOptionPane.WARNING_MESSAGE);
            return;
        }else{
            try{
                FileReader fr = new FileReader("data/assessmentType.txt");
                BufferedReader br = new BufferedReader(fr);

                String line = null;
                List<String> lines = new ArrayList<>();

                while((line = br.readLine()) != null){
                    String[] items = line.split(", ");
                    if (items[0].equals(id)){
                        line = String.format("%s, %s, %s", id, newName, newDesc);
                    }
                    lines.add(line);
                }

                br.close();
                fr.close();

                // Write information back to assessmentType.txt file
                FileWriter fw = new FileWriter("data/assessmentType.txt");
                BufferedWriter bw = new BufferedWriter(fw);

                for(String item : lines){
                    bw.write(item);
                    bw.newLine();
                }

                bw.close();
                fw.close();
            }catch(IOException e){
                JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
            }
            JOptionPane.showMessageDialog(null, String.format("%s has been updated successfully", newName), "Success", JOptionPane.INFORMATION_MESSAGE);
            loadTable();
            txtId.setText("");
            txtName.setText("");
            txtDesc.setText("");
            
            txtId.setEditable(true);
            txtId.requestFocusInWindow();
            
            assessmentTable.clearSelection();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        String id = String.format(txtId.getText()).trim();
        
        row = assessmentTable.getSelectedRow();
        
        if(row == -1){
            JOptionPane.showMessageDialog(null, "Please select a row to delete", "Empty Values", JOptionPane.WARNING_MESSAGE);
            return;
        }else{
            // get deleted department name
            String name = assessmentTable.getValueAt(row, 1).toString().trim();
            
            int confirm = JOptionPane.showConfirmDialog(null, String.format("Are you sure you want to delete %s? ", name), "Confirm Delete", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.NO_OPTION) {
                return; 
            }
            try{
            FileReader fr = new FileReader("data/assessmentType.txt");
            BufferedReader br = new BufferedReader(fr);
            
            String line = null;
            List<String> lines = new ArrayList<>();
            
            while((line = br.readLine()) != null){
                String[] items = line.split(", ");
                if (!items[0].equals(id)){
                    lines.add(line);
                }
            }
            
            br.close();
            fr.close();
            
            // Write information back to assessmentType.txt file
            FileWriter fw = new FileWriter("data/assessmentType.txt");
            BufferedWriter bw = new BufferedWriter(fw);
            
            for(String item : lines){
                bw.write(item);
                bw.newLine();
            }
            
            bw.close();
            fw.close();
            
            JOptionPane.showMessageDialog(null, String.format("%s has been removed successfully", name), "Success", JOptionPane.INFORMATION_MESSAGE);
            loadTable();
            txtId.setText("");
            txtName.setText("");
            txtDesc.setText("");
            
            txtId.setEditable(true);
            }catch(IOException e){
                JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        assessmentTable.clearSelection();
        txtId.requestFocusInWindow();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void assessmentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assessmentTableMouseClicked
        // TODO add your handling code here:
        row = assessmentTable.getSelectedRow();
        
        txtId.setText(String.valueOf(assessmentTable.getValueAt(row, 0)).trim());
        txtName.setText(String.valueOf(assessmentTable.getValueAt(row, 1)).trim());
        txtDesc.setText(String.valueOf(assessmentTable.getValueAt(row, 2)).trim());
        
        txtId.setEditable(false);
        txtDesc.requestFocusInWindow();
    }//GEN-LAST:event_assessmentTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIManageAssessmentType().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable assessmentTable;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JFormattedTextField txtId;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
