package medManager;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ryne
 */

import javax.swing.*;
import javax.swing.table.*;
import java.io.*;
import java.text.*;
import java.util.*;
import javax.swing.text.*;

public class GUIManageDepartments extends javax.swing.JFrame {
    int row = -1;
    private MedicalManager manager;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIManageDepartments.class.getName());
    private DefaultTableModel model = new DefaultTableModel();
    private String[] columns = {"Department ID", "Department Name", "Department Description"};

    /**
     * Creates new form GUIManageDepartment
     */
    public GUIManageDepartments() {
        initComponents();
    }
    
    public GUIManageDepartments(MedicalManager manager){
        initComponents();
        model.setColumnIdentifiers(columns);
        loadTable();
        this.manager = manager;
        txtId.requestFocusInWindow();
        
        // fix input for txtId
        try {
            MaskFormatter idMask = new MaskFormatter("D###");
            txtId.setFormatterFactory(new DefaultFormatterFactory(idMask));
        } catch (ParseException e) {
            // only triggered when mask format failed
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtDesc = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        deptTable = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtId = new javax.swing.JFormattedTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setText("Manage Departments");

        jLabel2.setText("Department ID: ");

        jLabel3.setText("Department Name: ");

        jLabel4.setText("Department Description: ");

        deptTable.setModel(model);
        deptTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deptTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(deptTable);

        btnAdd.setText("Add New Department");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setText("Update Department");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnRemove.setText("Remove Department");
        btnRemove.addActionListener(this::btnRemoveActionPerformed);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        btnClear.setText("Clear Selection");
        btnClear.addActionListener(this::btnClearActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnAdd)
                            .addGap(30, 30, 30)
                            .addComponent(btnUpdate)
                            .addGap(33, 33, 33)
                            .addComponent(btnRemove))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                .addComponent(txtName)
                                .addComponent(txtId))
                            .addGap(75, 75, 75)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClear)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnRemove))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnClear))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadTable(){
        model.setRowCount(0);
        
        try{
            FileReader fr = new FileReader("data/departments.txt");
            BufferedReader br = new BufferedReader(fr);
            
            String line = null;
            String[] items;
            
            while((line = br.readLine()) != null){
                items = line.split(", ");
                model.addRow(items);
            }
            
            fr.close();
            br.close();
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public boolean ifIdExist(String checkId){
        for(int row = 0; row < deptTable.getRowCount(); row++){
            String id = deptTable.getValueAt(row, 0).toString().trim();
            if (id.equals(checkId)){
                return true;
            }
        }
        return false;
    }

    private void deptTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deptTableMouseClicked
        // TODO add your handling code here:
        row = deptTable.getSelectedRow();
        
        txtId.setText(String.valueOf(deptTable.getValueAt(row, 0)).trim());
        txtName.setText(String.valueOf(deptTable.getValueAt(row, 1)).trim());
        txtDesc.setText(String.valueOf(deptTable.getValueAt(row, 2)).trim());
        
        txtId.setEditable(false);
        txtDesc.requestFocusInWindow();
    }//GEN-LAST:event_deptTableMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String id = String.format(txtId.getText()).trim();
        String name = String.format(txtName.getText()).trim();
        String desc = String.format(txtDesc.getText()).trim();
        
        if(id.isEmpty() || name.isEmpty() || desc.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill in all field", "Empty Values", JOptionPane.WARNING_MESSAGE);
            return;
        }else if(ifIdExist(id)){
            JOptionPane.showMessageDialog(null, "Department ID is duplicated", "Duplicated Department ID", JOptionPane.WARNING_MESSAGE);
            return;
        }else{
            manager.createDepartment(id, name, desc);
            JOptionPane.showMessageDialog(null, String.format("New department: %s is added successfully", name), "Success", JOptionPane.INFORMATION_MESSAGE);
            loadTable();
            txtId.setText("");
            txtName.setText("");
            txtDesc.setText("");
            
            txtId.setEditable(true);
            txtId.requestFocusInWindow();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new GUIManagerMenu(manager).setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String id = String.format(txtId.getText()).trim();
        String name = String.format(txtName.getText()).trim();
        String desc = String.format(txtDesc.getText()).trim();
        
        row = deptTable.getSelectedRow();
        
        if(row == -1){
            JOptionPane.showMessageDialog(null, "Please select a row to edit", "Empty Values", JOptionPane.WARNING_MESSAGE);
            return;
        }else if(name.isEmpty() || desc.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill in all field", "Empty Values", JOptionPane.WARNING_MESSAGE);
            return;
        }else{
            manager.updateDepartment(id, name, desc);
            JOptionPane.showMessageDialog(null, String.format("%s has been updated successfully", name), "Success", JOptionPane.INFORMATION_MESSAGE);
            loadTable();
            txtId.setText("");
            txtName.setText("");
            txtDesc.setText("");
            
            txtId.setEditable(true);
            txtId.requestFocusInWindow();
            
            deptTable.clearSelection();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        String id = String.format(txtId.getText()).trim();
        
        row = deptTable.getSelectedRow();
        
        if(row == -1){
            JOptionPane.showMessageDialog(null, "Please select a row to delete", "Empty Values", JOptionPane.WARNING_MESSAGE);
            return;
        }else{
            // get deleted department name
            String name = deptTable.getValueAt(row, 1).toString().trim();
            
            int confirm = JOptionPane.showConfirmDialog(null, String.format("Are you sure you want to delete %s? ", name), "Confirm Delete", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.NO_OPTION) {
                return; 
            }
            try{
            FileReader fr = new FileReader("data/departments.txt");
            BufferedReader br = new BufferedReader(fr);
            
            String line = null;
            List<String> lines = new ArrayList<>();
            
            while((line = br.readLine()) != null){
                String[] items = line.split(", ");
                if (!items[0].equals(id)){
                    lines.add(line);
                }
            }
            
            br.close();
            fr.close();
            
            // Write information back to departments.txt file
            FileWriter fw = new FileWriter("data/departments.txt");
            BufferedWriter bw = new BufferedWriter(fw);
            
            for(String item : lines){
                bw.write(item);
                bw.newLine();
            }
            
            bw.close();
            fw.close();
            
            JOptionPane.showMessageDialog(null, String.format("%s has been removed successfully", name), "Success", JOptionPane.INFORMATION_MESSAGE);
            loadTable();
            txtId.setText("");
            txtName.setText("");
            txtDesc.setText("");
            
            txtId.setEditable(true);
            }catch(IOException e){
                JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        deptTable.clearSelection();
        txtId.requestFocusInWindow();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        deptTable.clearSelection();
        txtId.setEditable(true);
        txtId.setText(null);
        txtName.setText("");
        txtDesc.setText("");
        txtId.requestFocusInWindow();
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIManageDepartments().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTable deptTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JFormattedTextField txtId;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
