package medManager;


import java.text.*;
import javax.swing.*;
import javax.swing.table.*;
import javax.swing.text.*;
import java.io.*;
import java.util.ArrayList;
import java.util.List;
//import medicalManager.GUIManagerMenu;
//import medicalManager.MedicalManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ryne
 */
public class GUIManageDoctors extends javax.swing.JFrame {
    private MedicalManager manager;
    private int row = -1;
    private DefaultTableModel model = new DefaultTableModel();
    private String[] column = {"Doctor ID", "Doctor Name", "Department", "Employment Status"};
    
    // replace with the txt file name storing doctor name
    String docFile = "doctors.txt";
    // replace with the index of doctorId in the above file
    int idIndex = 0;
    // replace with the index of doctorName in the above file
    int nameIndex = 1;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIManageDoctors.class.getName());

    /**
     * Creates new form GUIManageDoctors
     */
    public GUIManageDoctors() {
        initComponents();
    }
    
    public GUIManageDoctors(MedicalManager manager) {
        initComponents();
        this.manager = manager;
        model.setColumnIdentifiers(column);
        txtId.setEditable(false);
        cmbDept.setSelectedIndex(-1);
        cmbStatus.setSelectedIndex(-1);
        
        // fix input for txtId
        try {
            MaskFormatter idMask = new MaskFormatter("D###");
            txtId.setFormatterFactory(new DefaultFormatterFactory(idMask));
        } catch (ParseException e) {
            // only triggered when mask format failed
            e.printStackTrace();
        }
        
        // insert departments to cmbDept
        try{
            FileReader fr = new FileReader("data/departments.txt");
            BufferedReader br = new BufferedReader(fr);
            
            String line = null;
            
            while((line = br.readLine()) != null){
                String[] items = line.split(", ");
                cmbDept.addItem(items[1]);
            }
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        cmbDept.setSelectedIndex(-1);
        loadTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        docTable = new javax.swing.JTable();
        btnback = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        cmbStatus = new javax.swing.JComboBox<>();
        cmbDept = new javax.swing.JComboBox<>();
        txtName = new javax.swing.JTextField();
        txtId = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setText("Manage Doctors");

        jLabel2.setText("Doctor ID: ");

        jLabel3.setText("Doctor Name: ");

        jLabel4.setText("Department: ");

        jLabel5.setText("Employment Status: ");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        docTable.setModel(model);
        docTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                docTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(docTable);

        btnback.setText("Back");
        btnback.addActionListener(this::btnbackActionPerformed);

        btnClear.setText("Clear Selection");
        btnClear.addActionListener(this::btnClearActionPerformed);

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnback)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClear))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtName)
                                .addComponent(cmbDept, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbStatus, javax.swing.GroupLayout.Alignment.TRAILING, 0, 189, Short.MAX_VALUE)))
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnback)
                    .addComponent(btnClear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadTable(){
        model.setRowCount(0);
        
        try{
            FileReader fr = new FileReader(docFile);
            BufferedReader br = new BufferedReader(fr);
            
            String line = null;
            String[] items;
            
            while((line = br.readLine()) != null){
                items = line.split(", ");
                model.addRow(items);
            }
            
            fr.close();
            br.close();
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new GUIManagerMenu(manager).setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        docTable.clearSelection();
        txtId.setEditable(true);
        txtId.setText(null);
        txtName.setText("");
        cmbDept.setSelectedIndex(-1);
        cmbStatus.setSelectedIndex(-1);
        txtId.requestFocusInWindow();
    }//GEN-LAST:event_btnClearActionPerformed

    private void docTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docTableMouseClicked
        // TODO add your handling code here:
        row = docTable.getSelectedRow();
        
        txtId.setText(String.valueOf(docTable.getValueAt(row, 0)));
        txtName.setText(String.valueOf(docTable.getValueAt(row, 1)));
        cmbDept.setSelectedItem(docTable.getValueAt(row, 2));
        cmbStatus.setSelectedItem(docTable.getValueAt(row, 3));
                
        txtId.setEditable(false);
        txtName.requestFocusInWindow();
    }//GEN-LAST:event_docTableMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        row = docTable.getSelectedRow();
        String newName = null;
        
        if(row == -1){
            JOptionPane.showMessageDialog(null, "Please select a row to edit", "Empty Values", JOptionPane.WARNING_MESSAGE);
            return;
        }else if(txtName.getText().isEmpty() || cmbDept.getSelectedIndex() == -1 || cmbStatus.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(null, "Please fill in all field", "Empty Values", JOptionPane.WARNING_MESSAGE);
            return;
        }else{
            try{
                String id = String.format(txtId.getText()).trim();
                newName = String.format(txtName.getText()).trim();
                String newDept = cmbDept.getSelectedItem().toString();
                String newStatus = cmbStatus.getSelectedItem().toString();

                FileReader fr = new FileReader(docFile);
                BufferedReader br = new BufferedReader(fr);

                String line = null;
                List<String> lines = new ArrayList<>();

                while((line = br.readLine()) != null){
                    String[] items = line.split(", ");
                    if (items[0].equals(id)){
                        line = String.format("%s, %s, %s, %s", id, newName, newDept, newStatus);
                    }
                    lines.add(line);
                }

                br.close();
                fr.close();

                // Write information back to docFile
                FileWriter fw = new FileWriter(docFile);
                BufferedWriter bw = new BufferedWriter(fw);

                for(String item : lines){
                    bw.write(item);
                    bw.newLine();
                }

                bw.close();
                fw.close();
            }catch(IOException e){
                JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            JOptionPane.showMessageDialog(null, String.format("%s has been updated successfully", newName), "Success", JOptionPane.INFORMATION_MESSAGE);
            loadTable();
            txtId.setText("");
            txtName.setText("");
            cmbDept.setSelectedIndex(-1);
            cmbStatus.setSelectedIndex(-1);
            
            txtId.setEditable(true);
            txtId.requestFocusInWindow();
            
            docTable.clearSelection();
            row = -1;
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIManageDoctors().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnback;
    private javax.swing.JComboBox<String> cmbDept;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JTable docTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField txtId;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
