package medManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ryne
 */

import java.io.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.*;
import javax.swing.text.*;
import java.text.*;
import java.time.*;
import java.time.format.*;

public class GUIManageShifts extends javax.swing.JFrame {
    private MedicalManager manager;
    private DefaultTableModel model = new DefaultTableModel();
    private String[] column = {"Shift ID", "Shift Date", "Start Time", "End Time", "Doctor ID", "Doctor Name"};
    int row = -1;
    // replace with the txt file name storing doctor name
    String docFile = "data/Doctor.txt";
    // replace with the index of doctorId in the above file
    int idIndex = 0;
    // replace with the index of doctorName in the above file
    int nameIndex = 1;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIManageShifts.class.getName());

    /**
     * Creates new form GUIManageShift
     */
    public GUIManageShifts() {
        initComponents();
    }
    
    public GUIManageShifts(MedicalManager manager) {
        initComponents();
        model.setColumnIdentifiers(column);
        loadTable();
        this.manager = manager;
        txtDocId.setEditable(false);
        
        // fix input for txtShiftId
        try {
            MaskFormatter idMask = new MaskFormatter("S###");
            txtShiftId.setFormatterFactory(new DefaultFormatterFactory(idMask));
        } catch (ParseException e) {
            // only triggered when mask format failed
            e.printStackTrace();
        }
        txtShiftId.requestFocusInWindow();

        // fix input for txtDate
        try {
            MaskFormatter dateMask = new MaskFormatter("####-##-##");
            txtDate.setFormatterFactory(new DefaultFormatterFactory(dateMask));
        } catch (ParseException e) {
            // only triggered when mask format failed
            e.printStackTrace();
        }
        
        // fix input for txtStartTime
        try {
            MaskFormatter startTimeMask = new MaskFormatter("##:##");
            txtStartTime.setFormatterFactory(new DefaultFormatterFactory(startTimeMask));
        } catch (ParseException e) {
            e.printStackTrace();
        }

        // fix input for txtEndTime
        try {
            MaskFormatter endTimeMask = new MaskFormatter("##:##");
            txtEndTime.setFormatterFactory(new DefaultFormatterFactory(endTimeMask));
        } catch (ParseException e) {
            e.printStackTrace();
        }
        
        // insert doctorName into cmbDocName
        try{
            FileReader fr = new FileReader(docFile);
            BufferedReader br = new BufferedReader(fr);

            String line = null;

            while((line = br.readLine()) != null){
                String[] items = line.split(", ");
                cmbDocName.addItem(items[nameIndex].trim());
            }

            fr.close();
            br.close();
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
        cmbDocName.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        shiftTable = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtDate = new javax.swing.JFormattedTextField();
        txtStartTime = new javax.swing.JFormattedTextField();
        txtEndTime = new javax.swing.JFormattedTextField();
        cmbDocName = new javax.swing.JComboBox<>();
        txtDocId = new javax.swing.JFormattedTextField();
        txtShiftId = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setText("Manage Shifts");

        jLabel2.setText("Shift ID: ");

        jLabel3.setText("Shift Date: ");

        jLabel4.setText("Start Time: ");

        jLabel5.setText("End Time: ");

        jLabel6.setText("Doctor ID: ");

        btnAdd.setText("Add New Shift");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setText("Update Shift Information");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDel.setText("Remove Shift");
        btnDel.addActionListener(this::btnDelActionPerformed);

        shiftTable.setModel(model);
        shiftTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shiftTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(shiftTable);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        btnClear.setText("Clear Selection");
        btnClear.addActionListener(this::btnClearActionPerformed);

        jLabel7.setText("Doctor Name: ");

        cmbDocName.addActionListener(this::cmbDocNameActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addGap(44, 44, 44)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtDate)
                                            .addComponent(txtStartTime)
                                            .addComponent(txtEndTime, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                            .addComponent(txtShiftId)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cmbDocName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtDocId, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClear)))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addGap(66, 66, 66)
                                .addComponent(btnUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDel)))
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtShiftId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDocId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbDocName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDel))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnClear))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadTable(){
        model.setRowCount(0);
        
        // filter past shifts
        List<String[]> tempShift = new ArrayList<>();
        try{
            FileReader fr = new FileReader("data/shiftRoster.txt");
            BufferedReader br = new BufferedReader(fr);
            
            String line = null;
            
            while((line = br.readLine()) != null){
                String[] items = line.split(", ");
                
                // check on past shifts
                try{
                    LocalDate today = LocalDate.now();
                    LocalTime now = LocalTime.now();
                    LocalDate date = LocalDate.parse(items[1]);
                    LocalTime time = LocalTime.parse(items[2]);

                    if(date.isBefore(today)){
                        continue;
                    }else if(date.isEqual(today) && time.isBefore(now)){
                        continue;
                    }
                    tempShift.add(items);
                }catch(DateTimeParseException e){
                    JOptionPane.showMessageDialog(null, e, "Invalid Date Time", JOptionPane.ERROR_MESSAGE);
                }
            }
            
            fr.close();
            br.close();
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        // sort the list
        tempShift.sort(Comparator.comparing((String[] items) -> items[1]).thenComparing(items -> items[2]).thenComparing(items -> items[3]));
        
        // rewrite the filtered list
        try{
            FileWriter fw = new FileWriter("data/shiftRoster.txt");
            BufferedWriter bw = new BufferedWriter(fw);
            
            for(String[] line: tempShift){
                bw.write(String.join(", ", line));
                bw.newLine();
                model.addRow(line);
            }
            
            bw.close();
            fw.close();
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        // store all doctor information to a list
        List<String> tempDoc = new ArrayList<>();
        try{
            FileReader fr = new FileReader(docFile);
            BufferedReader br = new BufferedReader(fr);

            String line = null;

            while((line = br.readLine()) != null){
                tempDoc.add(line);
            }

            fr.close();
            br.close();
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }

        // insert information for the last column: Doctor Name
        for(int row = 0; row < shiftTable.getRowCount(); row++){
            String checkDocId = shiftTable.getValueAt(row, 4).toString().trim();
            String docName = null;
            
            for(String line : tempDoc){
                String[] items = line.split(", ");
                String docId = items[idIndex];
                if(docId.equals(checkDocId)){
                    docName = items[nameIndex];
                    break;
                }
            }
            
            shiftTable.setValueAt(docName, row, 5);
        }
    }
    
//    public void sortList(List<String[]> list){
//        list.sort(Comparator.comparing((String[] items) -> items[1]).thenComparing(items -> items[2]));
//    }
    
    public boolean ifIdExist(String checkId){
        for(int row = 0; row < shiftTable.getRowCount(); row++){
            String id = shiftTable.getValueAt(row, 0).toString().trim();
            if (id.equals(checkId)){
                return true;
            }
        }
        return false;
    }
    
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        shiftTable.clearSelection();
        txtShiftId.setEditable(true);
        txtShiftId.setText(null);
        txtDate.setText(null);
        txtStartTime.setText(null);
        txtEndTime.setText(null);
        cmbDocName.setSelectedIndex(-1);
        txtShiftId.requestFocusInWindow();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new GUIManagerMenu(manager).setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try{
            String shiftId = txtShiftId.getText();
            String strDate = txtDate.getText();
            String strStartTime = txtStartTime.getText();
            String strEndTime = txtEndTime.getText();
            String docId = txtDocId.getText();


            LocalDate today = LocalDate.now();
            LocalTime now = LocalTime.now();

            if(shiftId.contains(" ") || strDate.contains(" ") || strStartTime.contains(" ") || strEndTime.contains(" ")){
                JOptionPane.showMessageDialog(null, "Please fill in all field", "Empty Values", JOptionPane.WARNING_MESSAGE);
                return;
            }

            if(cmbDocName.getSelectedIndex() == -1){
                JOptionPane.showMessageDialog(null, "Please choose a doctor on duty", "Empty Values", JOptionPane.WARNING_MESSAGE);
                return;
            }
            String docName = cmbDocName.getSelectedItem().toString();


            if(ifIdExist(shiftId)){
                JOptionPane.showMessageDialog(null, "Shift ID is duplicated", "Duplicated Shift ID", JOptionPane.WARNING_MESSAGE);
                return;
            }
            // parse date and time to LocalDate and LocalTime
            LocalDate date = LocalDate.parse(strDate);
            LocalTime startTime = LocalTime.parse(strStartTime);
            LocalTime endTime = LocalTime.parse(strEndTime);

            if(date.isBefore(today)){
                JOptionPane.showMessageDialog(null, "Please enter a valid date", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                return;
            }else if(date.isEqual(today)){
                if(startTime.isBefore(now) || endTime.isBefore(now)){
                    JOptionPane.showMessageDialog(null, "Please enter a valid time", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            if(endTime.isBefore(startTime) || endTime.equals(startTime)){
                JOptionPane.showMessageDialog(null, "Please enter a valid end time", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            Duration duration = Duration.between(startTime, endTime);
            if(duration.toMinutes() < 480 || duration.toMinutes() > 1440){
                JOptionPane.showMessageDialog(null, "Shift duration should in between 8 to 24 hours", "Shift Duration Out of Range", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // save the new shift to shiftRoster.txt
            manager.designShift(shiftId, date, startTime, endTime, docId);
            JOptionPane.showMessageDialog(null, String.format("New shift successfully assigned to Doctor %s", docName), "Success", JOptionPane.INFORMATION_MESSAGE);
            
            // interface reload
            loadTable();
            txtShiftId.setText(null);
            txtDate.setValue(null);
            txtStartTime.setValue(null);
            txtEndTime.setValue(null);
            cmbDocName.setSelectedIndex(-1);
            txtShiftId.requestFocusInWindow();
        }catch(DateTimeParseException e){
            JOptionPane.showMessageDialog(null, "Please enter a valid date and time in the correct format", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void cmbDocNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDocNameActionPerformed
        // TODO add your handling code here:
        if(cmbDocName.getSelectedIndex() != -1){
            String docName = cmbDocName.getSelectedItem().toString();
            try{
                FileReader fr = new FileReader(docFile);
                BufferedReader br = new BufferedReader(fr);

                String line;

                while((line = br.readLine()) != null){
                    String[] items = line.split(", ");
                    if(items[nameIndex].equals(docName)){
                        txtDocId.setText(items[idIndex]);
                        break;
                    }
                }

                fr.close();
                br.close();
            }catch(IOException e){
                JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            txtDocId.setText("");
        }
        
        
    }//GEN-LAST:event_cmbDocNameActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if(shiftTable.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "Please select 1 row to edit", "Empty Value", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try{
            // input validation
            String shiftId = txtShiftId.getText();
            String newStrDate = txtDate.getText();
            String newStrStartTime = txtStartTime.getText();
            String newStrEndTime = txtEndTime.getText();
            String newDocId = txtDocId.getText();
            String docName = cmbDocName.getSelectedItem().toString();
            
            LocalDate today = LocalDate.now();
            LocalTime now = LocalTime.now();

            if(newStrDate.contains(" ") || newStrStartTime.contains(" ") || newStrEndTime.contains(" ")){
                JOptionPane.showMessageDialog(null, "Please fill in all field", "Empty Values", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // parse date and time to LocalDate and LocalTime
            LocalDate newDate = LocalDate.parse(newStrDate);
            LocalTime newStartTime = LocalTime.parse(newStrStartTime);
            LocalTime newEndTime = LocalTime.parse(newStrEndTime);

            if(newDate.isBefore(today)){
                JOptionPane.showMessageDialog(null, "Please enter a valid date", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                return;
            }else if(newDate.isEqual(today)){
                if(newStartTime.isBefore(now) || newEndTime.isBefore(now)){
                    JOptionPane.showMessageDialog(null, "Please enter a valid time", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                    return;
            }

            }if(newEndTime.isBefore(newStartTime) || newEndTime.equals(newStartTime)){
                JOptionPane.showMessageDialog(null, "Please enter a valid end time", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // modify the selected shift in shiftRoster.txt
            manager.modifyShift(shiftId, newDate, newStartTime, newEndTime, newDocId);
            JOptionPane.showMessageDialog(null, "The shift has been updated successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            
            // interface reload
            loadTable();
            txtShiftId.setText(null);
            txtDate.setValue(null);
            txtStartTime.setValue(null);
            txtEndTime.setValue(null);
            cmbDocName.setSelectedIndex(-1);
            txtShiftId.setEditable(true);
            txtShiftId.requestFocusInWindow();
        }catch(DateTimeParseException e){
            JOptionPane.showMessageDialog(null, "Please enter a valid date and time in the correct format", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void shiftTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shiftTableMouseClicked
        // TODO add your handling code here:
        row = shiftTable.getSelectedRow();
        
        txtShiftId.setText(String.valueOf(shiftTable.getValueAt(row, 0)));
        txtDate.setText(String.valueOf(shiftTable.getValueAt(row, 1)));
        txtStartTime.setText(String.valueOf(shiftTable.getValueAt(row, 2)));
        txtEndTime.setText(String.valueOf(shiftTable.getValueAt(row, 3)));
        cmbDocName.setSelectedItem(shiftTable.getValueAt(row, 5));
                
        txtShiftId.setEditable(false);
        txtDate.requestFocusInWindow();
    }//GEN-LAST:event_shiftTableMouseClicked

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        String id = String.format(txtShiftId.getText());
        
        row = shiftTable.getSelectedRow();
        
        if(row == -1){
            JOptionPane.showMessageDialog(null, "Please select a row to delete", "Empty Values", JOptionPane.WARNING_MESSAGE);
            return;
        }else{
            int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the selected shift? ", "Confirm Delete", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.NO_OPTION) {
                return; 
            }
            try{
            FileReader fr = new FileReader("data/shiftRoster.txt");
            BufferedReader br = new BufferedReader(fr);
            
            String line = null;
            List<String> lines = new ArrayList<>();
            
            while((line = br.readLine()) != null){
                String[] items = line.split(", ");
                if (!items[0].equals(id)){
                    lines.add(line);
                }
            }
            
            br.close();
            fr.close();
            
            // Write information back to shiftRoster.txt file
            FileWriter fw = new FileWriter("data/shiftRoster.txt");
            BufferedWriter bw = new BufferedWriter(fw);
            
            for(String item : lines){
                bw.write(item);
                bw.newLine();
            }
            
            bw.close();
            fw.close();
            
            JOptionPane.showMessageDialog(null, String.format("Selected shift has been removed successfully"), "Success", JOptionPane.INFORMATION_MESSAGE);
            loadTable();
            txtShiftId.setText(null);
            txtDate.setValue(null);
            txtStartTime.setValue(null);
            txtEndTime.setValue(null);
            cmbDocName.setSelectedIndex(-1);
            txtShiftId.setEditable(true);
            shiftTable.clearSelection();
            txtShiftId.requestFocusInWindow();
            }catch(IOException e){
                JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIManageShifts().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbDocName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable shiftTable;
    private javax.swing.JFormattedTextField txtDate;
    private javax.swing.JFormattedTextField txtDocId;
    private javax.swing.JFormattedTextField txtEndTime;
    private javax.swing.JFormattedTextField txtShiftId;
    private javax.swing.JFormattedTextField txtStartTime;
    // End of variables declaration//GEN-END:variables
}
